SELECT CASE WHEN to_regnamespace('bookstore') IS NULL THEN 'true' ELSE 'false' END AS install_bookstore \gset
\if :install_bookstore

BEGIN;

CREATE SCHEMA bookstore;
COMMENT ON SCHEMA bookstore IS 'Schemii tutorial dataset v1';

CREATE TABLE bookstore.publishers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL UNIQUE,
    country_code char(2) NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'),
    founded_year integer CHECK (founded_year BETWEEN 1400 AND 2100)
);

CREATE TABLE bookstore.authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    email varchar(255) UNIQUE,
    country_code char(2),
    biography text
);

CREATE TABLE bookstore.books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id bigint NOT NULL REFERENCES bookstore.publishers(id) ON DELETE RESTRICT,
    isbn char(13) NOT NULL UNIQUE CHECK (isbn ~ '^[0-9]{13}$'),
    title varchar(240) NOT NULL,
    published_on date,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    format varchar(20) NOT NULL CHECK (format IN ('hardcover', 'paperback', 'ebook')),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE bookstore.book_authors (
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE CASCADE,
    author_id bigint NOT NULL REFERENCES bookstore.authors(id) ON DELETE CASCADE,
    author_order smallint NOT NULL DEFAULT 1 CHECK (author_order > 0),
    PRIMARY KEY (book_id, author_id),
    UNIQUE (book_id, author_order)
);

CREATE TABLE bookstore.inventory (
    book_id bigint PRIMARY KEY REFERENCES bookstore.books(id) ON DELETE CASCADE,
    on_hand integer NOT NULL DEFAULT 0 CHECK (on_hand >= 0),
    reorder_level integer NOT NULL DEFAULT 5 CHECK (reorder_level >= 0),
    warehouse_bin varchar(20) NOT NULL UNIQUE,
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE bookstore.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    full_name varchar(160) NOT NULL,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    marketing_opt_in boolean NOT NULL DEFAULT false
);

CREATE TABLE bookstore.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES bookstore.customers(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'packed', 'shipped', 'cancelled')),
    ordered_at timestamp with time zone NOT NULL DEFAULT now(),
    shipped_at timestamp with time zone,
    CHECK (shipped_at IS NULL OR shipped_at >= ordered_at)
);

CREATE TABLE bookstore.order_items (
    order_id bigint NOT NULL REFERENCES bookstore.orders(id) ON DELETE CASCADE,
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    line_total numeric(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    PRIMARY KEY (order_id, book_id)
);

CREATE TABLE bookstore.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE CASCADE,
    customer_id bigint NOT NULL REFERENCES bookstore.customers(id) ON DELETE CASCADE,
    rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (book_id, customer_id)
);

CREATE INDEX books_title_idx ON bookstore.books USING btree (title);
CREATE INDEX orders_customer_ordered_idx ON bookstore.orders USING btree (customer_id, ordered_at DESC);
CREATE INDEX reviews_book_rating_idx ON bookstore.reviews USING btree (book_id, rating DESC);
CREATE INDEX books_metadata_idx ON bookstore.books USING gin (metadata);

CREATE FUNCTION bookstore.touch_inventory_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END
$$;

CREATE TRIGGER inventory_touch_updated_at
BEFORE UPDATE ON bookstore.inventory
FOR EACH ROW EXECUTE FUNCTION bookstore.touch_inventory_updated_at();

CREATE FUNCTION bookstore.order_total(target_order_id bigint) RETURNS numeric
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(sum(line_total), 0)::numeric
    FROM bookstore.order_items
    WHERE order_id = target_order_id
$$;

CREATE VIEW bookstore.book_catalog AS
SELECT b.id, b.isbn, b.title, p.name AS publisher, b.price, b.format,
       i.on_hand, string_agg(a.name, ', ' ORDER BY ba.author_order) AS authors
FROM bookstore.books b
JOIN bookstore.publishers p ON p.id = b.publisher_id
JOIN bookstore.inventory i ON i.book_id = b.id
JOIN bookstore.book_authors ba ON ba.book_id = b.id
JOIN bookstore.authors a ON a.id = ba.author_id
GROUP BY b.id, p.name, i.on_hand;

INSERT INTO bookstore.publishers (id, name, country_code, founded_year) VALUES
    (1, 'Northstar Press', 'US', 1988),
    (2, 'Harbor House', 'GB', 1974),
    (3, 'Maple Leaf Books', 'CA', 2003);

INSERT INTO bookstore.authors (id, name, email, country_code, biography) VALUES
    (1, 'Maya Chen', 'maya@example.test', 'CA', 'Writes practical guides to data systems.'),
    (2, 'Jon Bell', 'jon@example.test', 'GB', 'Historian and essayist.'),
    (3, 'Amara Okafor', 'amara@example.test', 'NG', 'Novelist focused on cities and community.'),
    (4, 'Luis Ortega', 'luis@example.test', 'MX', 'Chef and food photographer.'),
    (5, 'Priya Raman', 'priya@example.test', 'IN', 'Software architect and educator.');

INSERT INTO bookstore.books (id, publisher_id, isbn, title, published_on, price, format, metadata) VALUES
    (1, 1, '9780000000001', 'Practical PostgreSQL Patterns', '2025-02-11', 44.00, 'paperback', '{"topics":["postgresql","design"],"level":"intermediate"}'),
    (2, 1, '9780000000002', 'Reliable Data Systems', '2024-09-03', 58.50, 'hardcover', '{"topics":["databases","operations"]}'),
    (3, 2, '9780000000003', 'A Short History of Maps', '2021-05-18', 28.00, 'paperback', '{"topics":["history","cartography"]}'),
    (4, 3, '9780000000004', 'The City Between Rivers', '2023-10-24', 19.95, 'paperback', '{"topics":["fiction"]}'),
    (5, 3, '9780000000005', 'Weeknight Kitchens', '2025-04-08', 34.00, 'hardcover', '{"topics":["cooking"]}'),
    (6, 1, '9780000000006', 'Schema Design Workbook', '2026-01-20', 24.00, 'ebook', '{"topics":["postgresql","education"]}');

INSERT INTO bookstore.book_authors (book_id, author_id, author_order) VALUES
    (1, 1, 1), (1, 5, 2), (2, 5, 1), (3, 2, 1), (4, 3, 1), (5, 4, 1), (6, 1, 1);

INSERT INTO bookstore.inventory (book_id, on_hand, reorder_level, warehouse_bin) VALUES
    (1, 18, 5, 'A-01'), (2, 7, 4, 'A-02'), (3, 12, 4, 'B-01'),
    (4, 23, 6, 'B-02'), (5, 4, 5, 'C-01'), (6, 999, 0, 'DIGITAL');

INSERT INTO bookstore.customers (id, email, full_name, joined_at, marketing_opt_in) VALUES
    (1, 'alex@example.test', 'Alex Morgan', '2025-10-04 14:30:00+00', true),
    (2, 'sam@example.test', 'Sam Rivera', '2025-11-12 09:15:00+00', false),
    (3, 'taylor@example.test', 'Taylor Kim', '2026-01-08 17:45:00+00', true),
    (4, 'jordan@example.test', 'Jordan Patel', '2026-02-19 12:00:00+00', false);

INSERT INTO bookstore.orders (id, customer_id, status, ordered_at, shipped_at) VALUES
    (1, 1, 'shipped', '2026-06-02 10:30:00+00', '2026-06-03 16:00:00+00'),
    (2, 2, 'paid', '2026-06-05 13:20:00+00', NULL),
    (3, 1, 'packed', '2026-06-07 08:45:00+00', NULL),
    (4, 3, 'pending', '2026-06-08 19:10:00+00', NULL);

INSERT INTO bookstore.order_items (order_id, book_id, quantity, unit_price) VALUES
    (1, 1, 1, 44.00), (1, 4, 2, 19.95), (2, 2, 1, 58.50),
    (3, 5, 1, 34.00), (3, 6, 1, 24.00), (4, 3, 1, 28.00), (4, 4, 1, 19.95);

INSERT INTO bookstore.reviews (book_id, customer_id, rating, review_text, created_at) VALUES
    (1, 1, 5, 'Clear examples and useful tradeoffs.', '2026-06-06 09:00:00+00'),
    (4, 1, 4, 'Beautifully observed characters.', '2026-06-07 18:30:00+00'),
    (2, 2, 5, 'A practical reference for production work.', '2026-06-08 11:15:00+00'),
    (3, 3, 4, 'Concise and richly illustrated.', '2026-06-09 07:40:00+00');

SELECT setval(pg_get_serial_sequence('bookstore.publishers', 'id'), (SELECT max(id) FROM bookstore.publishers));
SELECT setval(pg_get_serial_sequence('bookstore.authors', 'id'), (SELECT max(id) FROM bookstore.authors));
SELECT setval(pg_get_serial_sequence('bookstore.books', 'id'), (SELECT max(id) FROM bookstore.books));
SELECT setval(pg_get_serial_sequence('bookstore.customers', 'id'), (SELECT max(id) FROM bookstore.customers));
SELECT setval(pg_get_serial_sequence('bookstore.orders', 'id'), (SELECT max(id) FROM bookstore.orders));
SELECT setval(pg_get_serial_sequence('bookstore.reviews', 'id'), (SELECT max(id) FROM bookstore.reviews));

COMMIT;

\endif

SELECT CASE WHEN
    to_regnamespace('bookstore') IS NOT NULL
    AND obj_description(to_regnamespace('bookstore'), 'pg_namespace') IS DISTINCT FROM 'Schemii tutorial dataset v2'
    AND obj_description(to_regnamespace('bookstore'), 'pg_namespace') IS DISTINCT FROM 'Schemii tutorial dataset v3'
    AND (
        SELECT count(*) = 9
        FROM pg_catalog.pg_class c
        JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'bookstore'
          AND c.relkind IN ('r', 'p')
          AND c.relname IN ('publishers', 'authors', 'books', 'book_authors', 'inventory', 'customers', 'orders', 'order_items', 'reviews')
    )
THEN 'true' ELSE 'false' END AS expand_bookstore \gset
\if :expand_bookstore

BEGIN;

INSERT INTO bookstore.publishers (id, name, country_code, founded_year) VALUES
    (4, 'Cedar & Ink', 'US', 1996),
    (5, 'Atlas Lantern', 'AU', 1981),
    (6, 'Juniper Editions', 'IE', 2008),
    (7, 'Redwood Academic', 'US', 1967),
    (8, 'Blue Heron Books', 'NZ', 1992),
    (9, 'Copperline Press', 'ZA', 2001),
    (10, 'Moonrise Media', 'JP', 2012)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bookstore.authors (id, name, email, country_code, biography)
SELECT author_number,
       (ARRAY['Avery','Cameron','Dara','Emery','Farah','Gideon','Hana','Inez','Jules','Kai','Leila','Micah'])[1 + ((author_number - 6) % 12)]
       || ' ' ||
       (ARRAY['Adler','Bennett','Costa','Dubois','El-Sayed','Fischer','Gupta','Hughes','Ito','Johnson','Kowalski','Laurent'])[1 + (((author_number - 6) / 12) % 12)],
       format('author%02s@example.test', author_number),
       (ARRAY['US','CA','GB','AU','IN','DE','FR','BR','JP','NG'])[1 + ((author_number - 1) % 10)],
       (ARRAY[
           'Explores how technology changes everyday work.',
           'Writes character-driven fiction about families and place.',
           'Researches history, trade, and material culture.',
           'Creates practical guides for curious lifelong learners.',
           'Combines field reporting with environmental science.'
       ])[1 + ((author_number - 1) % 5)]
FROM generate_series(6, 40) AS generated(author_number)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bookstore.books (id, publisher_id, isbn, title, published_on, price, format, metadata)
SELECT book_number,
       1 + ((book_number * 7) % 10),
       '978' || lpad(book_number::text, 10, '0'),
       (ARRAY['Hidden','Practical','Electric','Quiet','Brave','Modern','Forgotten','Essential','Curious','Infinite'])[1 + ((book_number - 1) % 10)]
       || ' ' ||
       (ARRAY['Gardens','Algorithms','Coastlines','Archives','Kitchens','Networks','Journeys','Workshops'])[1 + (((book_number - 1) / 10) % 8)]
       || format(' %s', book_number),
       date '2016-01-01' + ((book_number * 43) % 3600),
       (12 + ((book_number * 137) % 6200) / 100.0)::numeric(10,2),
       (ARRAY['hardcover','paperback','ebook'])[1 + ((book_number - 1) % 3)],
       jsonb_build_object(
           'topics', jsonb_build_array(
               (ARRAY['technology','history','fiction','cooking','science','business','travel','art'])[1 + ((book_number - 1) % 8)],
               (ARRAY['design','culture','leadership','nature','craft','society'])[1 + ((book_number - 1) % 6)]
           ),
           'level', (ARRAY['introductory','intermediate','advanced'])[1 + ((book_number - 1) % 3)],
           'pages', 120 + ((book_number * 17) % 480)
       )
FROM generate_series(7, 80) AS generated(book_number)
ON CONFLICT (id) DO NOTHING;

INSERT INTO bookstore.book_authors (book_id, author_id, author_order)
SELECT book_number, 1 + ((book_number * 7) % 40), 1
FROM generate_series(7, 80) AS generated(book_number)
ON CONFLICT (book_id, author_id) DO NOTHING;

INSERT INTO bookstore.book_authors (book_id, author_id, author_order)
SELECT book_number, 1 + ((book_number * 7 + 11) % 40), 2
FROM generate_series(9, 80, 3) AS generated(book_number)
ON CONFLICT (book_id, author_id) DO NOTHING;

INSERT INTO bookstore.inventory (book_id, on_hand, reorder_level, warehouse_bin, updated_at)
SELECT book_number,
       (book_number * 19) % 85,
       3 + (book_number % 9),
       format('%s-%02s', chr(65 + ((book_number - 1) / 10)::integer), 1 + ((book_number - 1) % 10)),
       timestamp with time zone '2026-06-10 12:00:00+00' - (book_number * interval '3 hours')
FROM generate_series(7, 80) AS generated(book_number)
ON CONFLICT (book_id) DO NOTHING;

INSERT INTO bookstore.customers (id, email, full_name, joined_at, marketing_opt_in)
SELECT customer_number,
       format('reader%03s@example.test', customer_number),
       (ARRAY['Alex','Blair','Casey','Devon','Elliot','Frankie','Gray','Harper','Indigo','Jamie','Kendall','Logan','Morgan','Noel','Oakley'])[1 + ((customer_number - 1) % 15)]
       || ' ' ||
       (ARRAY['Brooks','Campbell','Diaz','Evans','Foster','Green','Hayes','Ivanov','Jones','Khan'])[1 + (((customer_number - 1) / 15) % 10)],
       timestamp with time zone '2024-01-01 09:00:00+00' + (customer_number * interval '2 days 7 hours'),
       customer_number % 3 <> 0
FROM generate_series(5, 150) AS generated(customer_number)
ON CONFLICT (id) DO NOTHING;

WITH generated_orders AS (
    SELECT order_number,
           1 + ((order_number * 37) % 150) AS customer_id,
           (ARRAY['pending','paid','packed','shipped','cancelled'])[1 + ((order_number - 1) % 5)] AS status,
           timestamp with time zone '2025-06-01 08:00:00+00' + (order_number * interval '15 hours') AS ordered_at
    FROM generate_series(5, 500) AS generated(order_number)
)
INSERT INTO bookstore.orders (id, customer_id, status, ordered_at, shipped_at)
SELECT order_number, customer_id, status, ordered_at,
       CASE WHEN status = 'shipped' THEN ordered_at + ((1 + (order_number % 5)) * interval '1 day') END
FROM generated_orders
ON CONFLICT (id) DO NOTHING;

INSERT INTO bookstore.order_items (order_id, book_id, quantity, unit_price)
SELECT order_number,
       book.id,
       1 + ((order_number + item_number) % 3),
       book.price
FROM generate_series(5, 500) AS generated(order_number)
CROSS JOIN LATERAL generate_series(1, 1 + (order_number % 4)) AS items(item_number)
JOIN bookstore.books book ON book.id = 1 + ((order_number * 7 + item_number * 13) % 80)
ON CONFLICT (order_id, book_id) DO NOTHING;

INSERT INTO bookstore.reviews (book_id, customer_id, rating, review_text, created_at)
SELECT 1 + ((orders.id * 7 + 13) % 80),
       orders.customer_id,
       1 + ((orders.id * 11) % 5),
       (ARRAY[
           'Fast-paced and easy to recommend.',
           'Useful ideas with several memorable examples.',
           'A thoughtful read that rewards a second look.',
           'Strong opening chapters and a satisfying conclusion.',
           'Clear, approachable, and full of practical detail.',
           'An unexpected favorite from this year.'
       ])[1 + ((orders.id - 1) % 6)],
       orders.ordered_at + interval '12 days'
FROM bookstore.orders
WHERE orders.id BETWEEN 5 AND 500
  AND orders.status IN ('paid', 'packed', 'shipped')
ON CONFLICT (book_id, customer_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('bookstore.publishers', 'id'), (SELECT max(id) FROM bookstore.publishers));
SELECT setval(pg_get_serial_sequence('bookstore.authors', 'id'), (SELECT max(id) FROM bookstore.authors));
SELECT setval(pg_get_serial_sequence('bookstore.books', 'id'), (SELECT max(id) FROM bookstore.books));
SELECT setval(pg_get_serial_sequence('bookstore.customers', 'id'), (SELECT max(id) FROM bookstore.customers));
SELECT setval(pg_get_serial_sequence('bookstore.orders', 'id'), (SELECT max(id) FROM bookstore.orders));
SELECT setval(pg_get_serial_sequence('bookstore.reviews', 'id'), (SELECT max(id) FROM bookstore.reviews));

COMMENT ON SCHEMA bookstore IS 'Schemii tutorial dataset v2';

COMMIT;

\endif

SELECT CASE WHEN
    to_regnamespace('bookstore') IS NOT NULL
    AND (
        obj_description(to_regnamespace('bookstore'), 'pg_namespace') IS DISTINCT FROM 'Schemii tutorial dataset v3'
        OR to_regclass('bookstore.order_summary') IS NULL
    )
    AND to_regclass('bookstore.orders') IS NOT NULL
    AND to_regclass('bookstore.customers') IS NOT NULL
    AND to_regclass('bookstore.order_items') IS NOT NULL
THEN 'true' ELSE 'false' END AS add_dashboard_view \gset
\if :add_dashboard_view

BEGIN;

CREATE OR REPLACE VIEW bookstore.order_summary AS
SELECT orders.id AS order_id,
       orders.customer_id,
       customers.full_name AS customer_name,
       orders.status,
       orders.ordered_at,
       orders.shipped_at,
       orders.ordered_at::date AS order_date,
       COALESCE(sum(order_items.quantity), 0)::bigint AS item_count,
       COALESCE(sum(order_items.line_total), 0)::numeric(14,2) AS order_total
FROM bookstore.orders
JOIN bookstore.customers ON customers.id = orders.customer_id
LEFT JOIN bookstore.order_items ON order_items.order_id = orders.id
GROUP BY orders.id, customers.full_name;

COMMENT ON VIEW bookstore.order_summary IS 'One row per Mercury Books order for resettable Schemer examples';
COMMENT ON SCHEMA bookstore IS 'Schemii tutorial dataset v3';

COMMIT;

\endif
