SELECT CASE WHEN to_regnamespace('bookstore') IS NULL THEN 'true' ELSE 'false' END AS install_bookstore \gset
\if :install_bookstore

BEGIN;

CREATE SCHEMA bookstore;

CREATE TABLE bookstore.publishers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL UNIQUE,
    country_code char(2) NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'),
    founded_year integer CHECK (founded_year BETWEEN 1400 AND 2100)
);

CREATE TABLE bookstore.authors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(160) NOT NULL,
    email varchar(255) UNIQUE,
    country_code char(2),
    biography text
);

CREATE TABLE bookstore.books (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publisher_id bigint NOT NULL REFERENCES bookstore.publishers(id) ON DELETE RESTRICT,
    isbn char(13) NOT NULL UNIQUE CHECK (isbn ~ '^[0-9]{13}$'),
    title varchar(240) NOT NULL,
    published_on date,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    format varchar(20) NOT NULL CHECK (format IN ('hardcover', 'paperback', 'ebook')),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE bookstore.book_authors (
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE CASCADE,
    author_id bigint NOT NULL REFERENCES bookstore.authors(id) ON DELETE CASCADE,
    author_order smallint NOT NULL DEFAULT 1 CHECK (author_order > 0),
    PRIMARY KEY (book_id, author_id),
    UNIQUE (book_id, author_order)
);

CREATE TABLE bookstore.inventory (
    book_id bigint PRIMARY KEY REFERENCES bookstore.books(id) ON DELETE CASCADE,
    on_hand integer NOT NULL DEFAULT 0 CHECK (on_hand >= 0),
    reorder_level integer NOT NULL DEFAULT 5 CHECK (reorder_level >= 0),
    warehouse_bin varchar(20) NOT NULL UNIQUE,
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE bookstore.customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    full_name varchar(160) NOT NULL,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    marketing_opt_in boolean NOT NULL DEFAULT false
);

CREATE TABLE bookstore.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES bookstore.customers(id) ON DELETE RESTRICT,
    status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'packed', 'shipped', 'cancelled')),
    ordered_at timestamp with time zone NOT NULL DEFAULT now(),
    shipped_at timestamp with time zone,
    CHECK (shipped_at IS NULL OR shipped_at >= ordered_at)
);

CREATE TABLE bookstore.order_items (
    order_id bigint NOT NULL REFERENCES bookstore.orders(id) ON DELETE CASCADE,
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE RESTRICT,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    line_total numeric(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    PRIMARY KEY (order_id, book_id)
);

CREATE TABLE bookstore.reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id bigint NOT NULL REFERENCES bookstore.books(id) ON DELETE CASCADE,
    customer_id bigint NOT NULL REFERENCES bookstore.customers(id) ON DELETE CASCADE,
    rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
    review_text text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (book_id, customer_id)
);

CREATE INDEX books_title_idx ON bookstore.books USING btree (title);
CREATE INDEX orders_customer_ordered_idx ON bookstore.orders USING btree (customer_id, ordered_at DESC);
CREATE INDEX reviews_book_rating_idx ON bookstore.reviews USING btree (book_id, rating DESC);
CREATE INDEX books_metadata_idx ON bookstore.books USING gin (metadata);

CREATE FUNCTION bookstore.touch_inventory_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END
$$;

CREATE TRIGGER inventory_touch_updated_at
BEFORE UPDATE ON bookstore.inventory
FOR EACH ROW EXECUTE FUNCTION bookstore.touch_inventory_updated_at();

CREATE FUNCTION bookstore.order_total(target_order_id bigint) RETURNS numeric
LANGUAGE sql STABLE AS $$
    SELECT COALESCE(sum(line_total), 0)::numeric
    FROM bookstore.order_items
    WHERE order_id = target_order_id
$$;

CREATE VIEW bookstore.book_catalog AS
SELECT b.id, b.isbn, b.title, p.name AS publisher, b.price, b.format,
       i.on_hand, string_agg(a.name, ', ' ORDER BY ba.author_order) AS authors
FROM bookstore.books b
JOIN bookstore.publishers p ON p.id = b.publisher_id
JOIN bookstore.inventory i ON i.book_id = b.id
JOIN bookstore.book_authors ba ON ba.book_id = b.id
JOIN bookstore.authors a ON a.id = ba.author_id
GROUP BY b.id, p.name, i.on_hand;

INSERT INTO bookstore.publishers (id, name, country_code, founded_year) VALUES
    (1, 'Northstar Press', 'US', 1988),
    (2, 'Harbor House', 'GB', 1974),
    (3, 'Maple Leaf Books', 'CA', 2003);

INSERT INTO bookstore.authors (id, name, email, country_code, biography) VALUES
    (1, 'Maya Chen', 'maya@example.test', 'CA', 'Writes practical guides to data systems.'),
    (2, 'Jon Bell', 'jon@example.test', 'GB', 'Historian and essayist.'),
    (3, 'Amara Okafor', 'amara@example.test', 'NG', 'Novelist focused on cities and community.'),
    (4, 'Luis Ortega', 'luis@example.test', 'MX', 'Chef and food photographer.'),
    (5, 'Priya Raman', 'priya@example.test', 'IN', 'Software architect and educator.');

INSERT INTO bookstore.books (id, publisher_id, isbn, title, published_on, price, format, metadata) VALUES
    (1, 1, '9780000000001', 'Practical PostgreSQL Patterns', '2025-02-11', 44.00, 'paperback', '{"topics":["postgresql","design"],"level":"intermediate"}'),
    (2, 1, '9780000000002', 'Reliable Data Systems', '2024-09-03', 58.50, 'hardcover', '{"topics":["databases","operations"]}'),
    (3, 2, '9780000000003', 'A Short History of Maps', '2021-05-18', 28.00, 'paperback', '{"topics":["history","cartography"]}'),
    (4, 3, '9780000000004', 'The City Between Rivers', '2023-10-24', 19.95, 'paperback', '{"topics":["fiction"]}'),
    (5, 3, '9780000000005', 'Weeknight Kitchens', '2025-04-08', 34.00, 'hardcover', '{"topics":["cooking"]}'),
    (6, 1, '9780000000006', 'Schema Design Workbook', '2026-01-20', 24.00, 'ebook', '{"topics":["postgresql","education"]}');

INSERT INTO bookstore.book_authors (book_id, author_id, author_order) VALUES
    (1, 1, 1), (1, 5, 2), (2, 5, 1), (3, 2, 1), (4, 3, 1), (5, 4, 1), (6, 1, 1);

INSERT INTO bookstore.inventory (book_id, on_hand, reorder_level, warehouse_bin) VALUES
    (1, 18, 5, 'A-01'), (2, 7, 4, 'A-02'), (3, 12, 4, 'B-01'),
    (4, 23, 6, 'B-02'), (5, 4, 5, 'C-01'), (6, 999, 0, 'DIGITAL');

INSERT INTO bookstore.customers (id, email, full_name, joined_at, marketing_opt_in) VALUES
    (1, 'alex@example.test', 'Alex Morgan', '2025-10-04 14:30:00+00', true),
    (2, 'sam@example.test', 'Sam Rivera', '2025-11-12 09:15:00+00', false),
    (3, 'taylor@example.test', 'Taylor Kim', '2026-01-08 17:45:00+00', true),
    (4, 'jordan@example.test', 'Jordan Patel', '2026-02-19 12:00:00+00', false);

INSERT INTO bookstore.orders (id, customer_id, status, ordered_at, shipped_at) VALUES
    (1, 1, 'shipped', '2026-06-02 10:30:00+00', '2026-06-03 16:00:00+00'),
    (2, 2, 'paid', '2026-06-05 13:20:00+00', NULL),
    (3, 1, 'packed', '2026-06-07 08:45:00+00', NULL),
    (4, 3, 'pending', '2026-06-08 19:10:00+00', NULL);

INSERT INTO bookstore.order_items (order_id, book_id, quantity, unit_price) VALUES
    (1, 1, 1, 44.00), (1, 4, 2, 19.95), (2, 2, 1, 58.50),
    (3, 5, 1, 34.00), (3, 6, 1, 24.00), (4, 3, 1, 28.00), (4, 4, 1, 19.95);

INSERT INTO bookstore.reviews (book_id, customer_id, rating, review_text, created_at) VALUES
    (1, 1, 5, 'Clear examples and useful tradeoffs.', '2026-06-06 09:00:00+00'),
    (4, 1, 4, 'Beautifully observed characters.', '2026-06-07 18:30:00+00'),
    (2, 2, 5, 'A practical reference for production work.', '2026-06-08 11:15:00+00'),
    (3, 3, 4, 'Concise and richly illustrated.', '2026-06-09 07:40:00+00');

SELECT setval(pg_get_serial_sequence('bookstore.publishers', 'id'), (SELECT max(id) FROM bookstore.publishers));
SELECT setval(pg_get_serial_sequence('bookstore.authors', 'id'), (SELECT max(id) FROM bookstore.authors));
SELECT setval(pg_get_serial_sequence('bookstore.books', 'id'), (SELECT max(id) FROM bookstore.books));
SELECT setval(pg_get_serial_sequence('bookstore.customers', 'id'), (SELECT max(id) FROM bookstore.customers));
SELECT setval(pg_get_serial_sequence('bookstore.orders', 'id'), (SELECT max(id) FROM bookstore.orders));
SELECT setval(pg_get_serial_sequence('bookstore.reviews', 'id'), (SELECT max(id) FROM bookstore.reviews));

COMMIT;

\endif
