const assert = require("node:assert/strict");
const fs = require("node:fs");

const source = fs.readFileSync("src/schemii/schemer_web/app.js", "utf8");
const html = fs.readFileSync("src/schemii/schemer_web/index.html", "utf8");
const styles = fs.readFileSync("src/schemii/schemer_web/styles.css", "utf8");
const schemiiStyles = fs.readFileSync("src/schemii/web/styles.css", "utf8");
const client = fs.readFileSync("src/schemii/shared_web/postgres-client.js", "utf8");
const sessionClient = fs.readFileSync("src/schemii/shared_web/session-client.js", "utf8");
const sharedStyles = fs.readFileSync("src/schemii/shared_web/theme.css", "utf8");
const sharedUi = fs.readFileSync("src/schemii/shared_web/ui-components.js", "utf8");
const connectionDialog = html.slice(html.indexOf('id="connections-dialog"'), html.indexOf('id="dashboard-form-dialog"'));
const widgetEditor = html.slice(html.indexOf('id="widget-editor-dialog"'), html.indexOf('id="executed-sql-dialog"'));

assert.match(html, /<title>Schemer<\/title>/, "Schemer needs its own browser identity");
assert.match(html, /\/shared\/session-client\.js/, "Schemer must load the shared authenticated session client");
assert.match(html, /\/shared\/postgres-client\.js/, "Schemer must load the shared PostgreSQL browser client");
assert.match(html, /\/shared\/profile-manager\.js/, "Schemer must load shared profile contracts");
assert.match(source, /SchemiiShared\.createPostgresClient/, "Schemer must instantiate the shared PostgreSQL client");
assert.match(source, /path\.startsWith\("\/api\/dashboards"\)|value\.startsWith\("\/api\/dashboards"\)/, "dashboard requests must stay on the local Schemer API");
assert.match(source, /createProfileRepository\(\{ postgresClient: postgres \}\)/, "profile requests must use the shared profile repository");
assert.match(source, /postgres\.request\(`\/api\/postgres\/profiles\/\$\{encodeURIComponent\(profile\.id\)\}\/relations\?database=\$\{encodeURIComponent\(profile\.dbname\)\}&namespace=\$\{encodeURIComponent\(namespace\)\}`\)/, "relation browsing must use the shared exact-database catalog route");
assert.match(source, /postgres\.request\(`\/api\/postgres\/profiles\/\$\{encodeURIComponent\(catalog\.profileId\)\}\/relation\?database=[\s\S]*&relation=\$\{encodeURIComponent\(relation\.name\)\}`\)/, "relation selection must inspect one exact catalog identity");
assert.match(source, /selectedRelationIdentity = \{[\s\S]*profileId: descriptor\.profileId,[\s\S]*database: descriptor\.database,[\s\S]*namespace: descriptor\.namespace,[\s\S]*relation: descriptor\.relation,[\s\S]*kind: descriptor\.kind,[\s\S]*fingerprint: descriptor\.fingerprint/, "inspected relation identity must retain its stable catalog fingerprint");
assert.doesNotMatch(connectionDialog, /relation-browser/, "global Data sources must remain connection management only");
assert.match(widgetEditor, /relation-browser[\s\S]*Tables, views, and materialized views/, "each widget editor needs its own supported relation browser");
assert.match(widgetEditor, /id="widget-editor-name"[^>]*required[^>]*maxlength="128"[^>]*aria-label="Widget name"/, "the widget editor needs an explicit bounded name field");
assert.match(widgetEditor, />Visualization<[\s\S]*>Filters/, "the widget editor must present visualization roles and filters in connected tabs");
for (const section of ["source", "query", "filters", "sort", "detail"]) assert.match(widgetEditor, new RegExp(`data-editor-section="${section}"`), `widget editor needs a separate ${section} filing tab`);
assert.doesNotMatch(widgetEditor, /data-editor-section="visualization"/, "visualization controls belong beside their groupings and measures rather than in a disconnected tab");
assert.match(widgetEditor, /id="widget-query-editor"[\s\S]*id="widget-query-heading"[\s\S]*id="apply-widget-query"/, "the per-widget editor needs separate query views and an explicit apply action");
assert.match(source, /for \(const label of \["#", "Column", "PostgreSQL type", "Nullability", "Suggested roles"\]\)/, "relation inspection must display ordered PostgreSQL column metadata and advisory roles");
assert.match(source, /for \(const suggestion of column\.suggestions\)[\s\S]*badge\.textContent = suggestion/, "column role suggestions must render as advisory labels");
assert.doesNotMatch(source, /widget\.configuration\.(?:dimension|measure|date|identifier)|widget\.configuration\[["'](?:dimension|measure|date|identifier)/, "role suggestions must not silently change widget configuration");
assert.match(source, /\/relation\/preview`[\s\S]*method: "POST"[\s\S]*source: exactSourceIdentity\(descriptor\), offset: 0, limit: 20/, "source preview must send one verified identity with an explicit bound");
assert.match(source, /function renderRelationPreview\(result, container\)[\s\S]*for \(const column of result\.columns\)[\s\S]*result\.rows/, "source preview must render bounded rows through DOM APIs");
assert.match(html, /class="relation-detail" id="relation-detail"/, "the relation browser needs a catalog detail pane");
assert.match(source, /function exactSourceIdentity\(descriptor\)[\s\S]*profileId: descriptor\.profileId[\s\S]*fingerprint: descriptor\.fingerprint[\s\S]*const source = exactSourceIdentity\(descriptor\)[\s\S]*widget\.configuration = \{ source,[\s\S]*markDashboardChanged\(true\)/, "Edit mode must assign exactly one verified source identity to a widget");
assert.match(source, /sharedIconButton\(\{ icon: "edit"[\s\S]*dataset: \{ action: "edit-widget" \}[\s\S]*action === "edit-widget"[\s\S]*openWidgetEditor\(widgetId\)/, "every Edit-mode tile must expose a shared graphical Edit action that opens its own widget editor");
assert.match(source, /function commitWidgetEditorName\(\)[\s\S]*\.value\.trim\(\)[\s\S]*Widget name is required[\s\S]*widget\.title = title[\s\S]*renderDashboard\(\)[\s\S]*markDashboardChanged\(true\)/, "valid widget name edits must update the card and enter the dashboard autosave flow");
assert.match(source, /widgetEditorName\.addEventListener\("change", commitWidgetEditorName\)[\s\S]*event\.key !== "Enter"[\s\S]*commitWidgetEditorName\(\)/, "widget names must commit on change or Enter");
assert.match(source, /const widget = activeDashboard\?\.dashboard\.widgets\.find\(item => item\.id === editedWidgetId\)[\s\S]*const source = exactSourceIdentity\(descriptor\)[\s\S]*widget\.configuration = \{ source,/, "source assignment must target only the widget being edited");
assert.doesNotMatch(source, /widgetSelect|Widget receiving this source/, "the widget editor must not assign one widget's source through a global widget picker");
assert.match(source, /function openWidgetEditor\(widgetId\)[\s\S]*relationDetail\.replaceChildren\(\)[\s\S]*relationDetail\.hidden = true[\s\S]*currentSource[\s\S]*inspectSelectedRelation\(catalog, relation\)/, "widget editor reopen must clear stale controls and restore only that widget's saved source");
assert.match(source, /assign\.disabled = !editMode[\s\S]*widget\.configuration = \{\}/, "View mode must not assign sources and Edit mode must support clearing one");
assert.match(source, /sourceLabel\.textContent = `\$\{source\.database\}\.\$\{source\.namespace\}\.\$\{source\.relation\}\$\{suffix\}`/, "sourced widgets must display their exact relation identity and verification state");
assert.match(source, /\/relation\/verify`[\s\S]*method: "POST", body: JSON\.stringify\(\{ source \}\)/, "live source checks must send the complete saved source snapshot to the dedicated verifier");
assert.match(source, /async function verifyDashboardSources\(\)[\s\S]*state: "checking"[\s\S]*code: error\.code[\s\S]*renderDashboard\(\)/, "dashboard loading must visibly verify every persisted source");
assert.match(source, /function sourceChangeMessage\(result\)[\s\S]*missingColumns[\s\S]*changedColumns[\s\S]*addedColumns/, "catalog changes must report named missing, changed, and added columns");
assert.match(source, /function renderSourceChangeNotice\(verification\)[\s\S]*relation-change-notice/, "widget editors must display catalog-change details without rewriting the source");
assert.match(source, /widget\.configuration\?\.source && verification\?\.state !== "verified"[\s\S]*return;/, "unverified or stale widget sources must not open results");
assert.match(source, /if \(profilesLoading\) return profilesLoading[\s\S]*generation !== relationCatalogGeneration/, "concurrent profile and relation loads must not clear newer catalog inspection state");
assert.match(source, /connections-button[\s\S]*if \(!profiles\.length\) await loadProfiles\(\)/, "opening an already loaded source browser must not clear its inspected relation");
assert.match(source, /replaceChildren/, "connection metadata must render through DOM APIs");
assert.doesNotMatch(source, /innerHTML|insertAdjacentHTML|eval\(/, "connection metadata must not be interpreted as code or HTML");
assert.match(source, /dashboard_conflict/, "stale dashboard writes must stop autosave");
assert.match(source, /dashboard\.viewport\[mode\]/, "desktop and mobile viewport state must be stored independently");
assert.match(source, /const editLabel = editMode \? "Finish editing" : "Edit dashboard"[\s\S]*classList\.toggle\("active", editMode\)[\s\S]*tooltipController\.update\(elements\.editModeButton, editLabel\)/, "the shared Edit icon must expose its active state and current action through its tooltip");
assert.match(source, /function setEditMode\(enabled, flush = true\)[\s\S]*const modeChanged = editMode !== nextEditMode[\s\S]*if \(modeChanged\) renderDashboard\(\)/, "changing dashboard mode must rebuild cards so Edit-only visualization controls are created and removed");
assert.doesNotMatch(source, /widget-resize-handle|reorderDesktopWidget|packDesktopLayout|elements\.canvas\.addEventListener\("pointer(?:down|move|up)"/, "dashboard cards must not support freeform positioning or resizing");
assert.match(source, /card\.draggable = editMode[\s\S]*addEventListener\("dragstart"[\s\S]*addEventListener\("drop"/, "Edit mode must support drag-and-drop tile ordering");
assert.match(source, /function swapWidgets\(widgetId, targetId\)[\s\S]*\[widgets\[sourceIndex\], widgets\[targetIndex\]\]/, "center overlap must swap the dragged and target widgets in the dashboard model");
assert.match(source, /dragCenterOffset[\s\S]*center\.x >= rect\.left[\s\S]*center\.y <= rect\.bottom/, "swap detection must use the dragged widget center crossing a target widget");
assert.match(source, /function animateWidgetSwap\(previousRects\)[\s\S]*card\.animate\(\[\{ transform:[\s\S]*duration: 260/, "widget swaps must animate from their previous grid positions");
assert.match(source, /function finishWidgetDrag\(\)[\s\S]*persistWidgetOrder\(activeDashboard\.dashboard\.widgets, false\)/, "animated swaps must persist when dragging finishes without interrupting the animation");
assert.match(source, /move-widget-earlier[\s\S]*move-widget-later/, "tile ordering must also provide keyboard-accessible controls");
assert.match(source, /icon: "edit"[\s\S]*icon: "earlier"[\s\S]*icon: "later"[\s\S]*icon: "duplicate"[\s\S]*icon: "delete"[\s\S]*className: "danger"/, "widget edit actions must use shared graphical controls and the shared danger state");
assert.match(styles, /\.widget-edit-controls \{[^}]*display: none !important;[^}]*gap: 4px !important;[^}]*\}[\s\S]*\.dashboard-edit-mode \.widget-edit-controls \{[^}]*display: flex !important;[^}]*width: auto;[^}]*flex: 0 0 auto;/, "widget edit icons must stay in the same header row as View SQL");
assert.match(source, /widget\.layout\.mobile\.order = index/, "reordering must keep mobile ordering aligned with the widget sequence");
assert.match(html, /id="widget-focus"[\s\S]*id="widget-inspector"/, "expanded widgets need a workspace view and inspector drawer");
assert.doesNotMatch(html, /widget-focus-head|close-widget-focus/, "expanded widgets must use their own header rather than a redundant outer header");
assert.match(source, /function openWidgetFocus\(widgetId\)/, "dashboard cards must open the expanded widget workspace");
assert.match(styles, /\.dashboard-workspace\.widget-focus-open \{ overflow: hidden; \}/, "expanded widget and detail panes must hide the underlying dashboard scrollbar");
assert.match(source, /openWidgetFocus\(card\.dataset\.widgetId\)/, "keyboard activation must open the expanded widget workspace");
assert.match(source, /focusedSourceRect = sourceCard\?\.getBoundingClientRect\(\)/, "expanded widgets must animate from the selected tile geometry");
assert.match(source, /focusedSourceRect\.width \/ target\.width[\s\S]*scale\(1\)/, "expanded widgets must scale from the tile instead of sliding in");
assert.match(source, /widgetInspector\.classList\.add\("dismissed"\)[\s\S]*widgetFocus\.classList\.add\("inspector-dismissed"\)/, "tile expansion must start without the inspector drawer");
assert.match(source, /\[data-inspect-metric\]/, "only metric-level targets may open the widget inspector");
assert.match(source, /\.metric-sparkline i[\s\S]*\.status-legend > span[\s\S]*querySelectorAll\("tbody tr"\)/, "bars, status values, and table rows must be individually inspectable");
assert.match(source, /function populationTable\(filters\)/, "metric inspection must render the selected population as a table");
assert.match(source, /const DATE_BUCKETS = \["Jun 1–4"[\s\S]*"Jun 28–30"\]/, "KPI bars must represent explicit order-date buckets");
assert.match(source, /bar\.dataset\.barLabel = date[\s\S]*bar\.dataset\.barValue = amount/, "expanded KPI bars must expose their date and value labels");
assert.match(source, /field: "Order date"[\s\S]*field: "Bucket value"/, "KPI bar selections must expose structured filters");
assert.match(source, /function populationRows\(filters\)[\s\S]*row\[6\] >= Number\(dates\[1\]\)/, "preview populations must filter by the selected date bucket");
assert.match(html, /id="view-inspector-sql"[\s\S]*id="executed-sql-dialog"/, "population results need an executed-SQL popup");
assert.match(source, /viewSql\.dataset\.action = "view-widget-sql"/, "every widget tile needs a View SQL button");
assert.match(source, /executedSqlByResult\.get\(`\$\{widget\.id\}:\$\{population \? "population" : "widget"\}`\)/, "widget and population results must use separate SQL provenance");
assert.match(source, /No SQL was executed for this static preview result/, "preview widgets must not claim that invented SQL was executed");
assert.match(source, /execution\?\.sql[\s\S]*execution\?\.parameters/, "the popup must show the executed parameterized statement and its bound values");
assert.match(source, /function defaultWidgetQuery\(\)[\s\S]*version: 2[\s\S]*dimensions:[\s\S]*measures:[\s\S]*filters:[\s\S]*sort:[\s\S]*limit:/, "widget query drafts must use the versioned grouped-filter contract");
assert.match(source, /function renderWidgetQueryDraft\(\)[\s\S]*dimensionTitle[\s\S]*measureTitle[\s\S]*Filters[\s\S]*Sort/, "one widget editor must configure visualization-specific dimensions and measures, filters, and sorting");
assert.match(source, /const querySections = visualizationMode === "kpi" \? \[visualization, measures\] : \[visualization, dimensions, measures\][\s\S]*const views = \{[\s\S]*query:[\s\S]*sections: querySections[\s\S]*filters:[\s\S]*sections: \[filters\][\s\S]*sort:[\s\S]*sections: \[sorting, tablePresentation\]/, "visualization roles, filters, sorting, and table presentation must render in coherent content views");
assert.match(source, /groupingPicker\.className = "grouping-picker"[\s\S]*checkbox\.type = visualizationMode === "table" \? "checkbox" : "radio"[\s\S]*visualization-dimension-/, "tables need multi-select dimensions while single-dimension visualizations need replaceable radio choices");
assert.match(source, /Conditions inside a group use AND[\s\S]*\+ OR group[\s\S]*filter-condition-join[\s\S]*separator\.textContent = "AND"/, "filters must visibly group AND conditions inside OR groups");
assert.match(source, /function filterOptionsForColumn\(column\)[\s\S]*Contains[\s\S]*Greater than[\s\S]*column\.type\.toLowerCase\(\) === "boolean"/, "filter operators must be selected from PostgreSQL column types");
assert.match(source, /function filterInputType\(type\)[\s\S]*return "date"[\s\S]*return "datetime-local"/, "date and timestamp filters need distinct typeable calendar modes");
const calendarSource = source.slice(source.indexOf("function queryCalendarInput"), source.indexOf("function queryTextarea"));
for (const contract of ["query-calendar-grid", "Previous month", "Today", "Clear"]) assert.match(calendarSource, new RegExp(contract), "date filters need a themed typeable calendar instead of the browser-native popup");
assert.match(source, /function queryFilterInput\(value, onChange, columnType\)[\s\S]*queryCalendarInput\(value, onChange[\s\S]*queryCalendarInput\(value, onChange, true\)/, "date and timestamp filter values must route through the themed calendar control");
assert.match(source, /addEventListener\("click"[\s\S]*query-calendar-popup:not\(\[hidden\]\)[\s\S]*control\?\.contains\(event\.target\)[\s\S]*popup\.hidden = true/, "calendar popups must close after an outside click");
assert.match(source, /\["between", "Between"\][\s\S]*filter-between-values[\s\S]*queryLabel\("From"[\s\S]*queryLabel\("To"/, "numeric and temporal between filters need two explicit bounds");
assert.match(source, /aggregationOptions = \[\["count_rows"[\s\S]*"count"[\s\S]*"sum"[\s\S]*"average"[\s\S]*"minimum"[\s\S]*"maximum"/, "the editor must expose all Phase 3 aggregate operations");
assert.match(source, /Sort rows are applied top to bottom[\s\S]*\+ Sort column[\s\S]*widgetQueryDraft\.sort\.forEach\(\(item, sortIndex\)[\s\S]*Order \$\{sortIndex \+ 1\}[\s\S]*\[\["Up", -1\], \["Down", 1\]\][\s\S]*splice\(sortIndex \+ offset, 0, item\)/, "multiple sort columns must expose and preserve their ORDER BY priority");
assert.match(source, /function defaultTablePresentation\(query\)[\s\S]*dimensions, \.\.\.query\.measures[\s\S]*width: 160[\s\S]*pageSize: 25/, "aggregate reports need deterministic presentation defaults without changing the query");
assert.match(source, /function reconcileTablePresentation\(query, presentation = null\)[\s\S]*for \(const kind of \["dimension", "measure"\]\)[\s\S]*hidden: Boolean[\s\S]*pinned: Boolean/, "table presentation reconciliation must retain dimensions before measures and preserve hidden fields");
assert.match(source, /function defaultVisualization\(query\)[\s\S]*mode: "table"[\s\S]*kpi: \{ measureIds:[\s\S]*bar: \{ dimensionId, measureIds:[\s\S]*line: \{ dimensionId, measureIds:[\s\S]*donut: \{ dimensionId, measureId:/, "visualizations need deterministic per-mode suggestions without rewriting the query");
assert.match(source, /function reconcileVisualization\(query, visualization = null\)[\s\S]*visualization\?\.selections\?\.kpi[\s\S]*visualization\?\.selections\?\.bar[\s\S]*visualization\?\.selections\?\.line[\s\S]*visualization\?\.selections\?\.donut/, "each visualization mode must restore its own still-valid field selections");
assert.match(source, /selection\?\.dimensionId === null \? \(query\.dimensions\.length === 1 \? query\.dimensions\[0\]\.id : null\)/, "existing charts with one grouping must recover a missing visualization dimension without rewriting the query");
assert.match(source, /function editorVisualizationSection\(\)[\s\S]*Aggregate table[\s\S]*KPI[\s\S]*Grouped bar[\s\S]*Line[\s\S]*Donut[\s\S]*portVisualizationRoles/, "the widget editor needs one visualization selector that ports roles between compatible modes");
assert.match(source, /function portVisualizationRoles\(sourceMode, targetMode\)[\s\S]*source\.dimensionIds\[0\][\s\S]*carriedMeasures[\s\S]*targetMode === "donut"/, "mode changes must carry compatible roles and truncate only the active role selection for narrower visualizations");
assert.match(source, /function editorVisualizationSample\(mode\)[\s\S]*visualization-sample-\$\{mode\}[\s\S]*mode === "table"[\s\S]*mode === "kpi"[\s\S]*mode === "bar"[\s\S]*mode === "line"[\s\S]*Appearance only - no data/, "each visualization selector needs a decorative static appearance sample that is explicitly not data");
assert.match(source, /Rows and columns for detailed comparisons[\s\S]*Headline values for quick status checks[\s\S]*Bars compare categories[\s\S]*Lines show change[\s\S]*Slices show how categories/, "static visualization samples need brief mode-specific descriptions");
assert.match(source, /markVisualizationRole\(dimensions[\s\S]*Choose a dimension[\s\S]*markVisualizationRole\(measures[\s\S]*Choose numeric values/, "the editor must highlight visualization-specific dimension and measure blocks that need values");
assert.match(source, /query: \{ heading: "Visualization, Dimensions & Measures"[\s\S]*sections: querySections/, "visualization and its bespoke query roles must share one editor tab");
assert.doesNotMatch(source, /function renderVisualizationControls|renderVisualizationControls\(/, "visualization controls must not clutter dashboard tiles");
assert.match(source, /queryGroup\("Aggregate table"[\s\S]*Presentation only[\s\S]*Display label[\s\S]*Width \(px\)[\s\S]*Hidden[\s\S]*Pin left[\s\S]*Rows per page/, "the editor must expose aggregate table order, labels, widths, visibility, pinning, and page size");
assert.match(source, /const sourceSnapshot = clone\(widget\.configuration\.source\)[\s\S]*const querySnapshot = clone\(query\)[\s\S]*const executionQuerySnapshot = queryForVisualization[\s\S]*\/relation\/query`[\s\S]*JSON\.stringify\(\{ source: sourceSnapshot, query: executionQuerySnapshot \}\)/, "widget execution must project immutable query snapshots to the active visualization roles");
assert.match(source, /const draft = clone\(widgetQueryDraft\)[\s\S]*const tableDraft = reconcileTablePresentation[\s\S]*await executeWidgetQuery\(widget, draft, \{ publish: false, visualization: visualizationDraft \}\)[\s\S]*widget\.configuration = \{ source, query: draft, table: tableDraft,/, "query, table, and visualization drafts must execute successfully without publishing before explicit apply persists them");
assert.match(source, /let queryExecuted = false[\s\S]*queryExecuted = true[\s\S]*Query ran successfully\. Saving the dashboard[\s\S]*await flushPendingSave\(\)[\s\S]*Query applied and saved/, "query apply must not report success until dashboard persistence completes");
assert.match(source, /widget\.kind = "aggregate_report"[\s\S]*widget\.configuration = \{ source, query: draft, table: tableDraft,/, "a successfully applied query must persist a first-class aggregate report and its presentation");
assert.match(source, /queryExecuted \? "Query ran, but the dashboard could not be saved\.[\s\S]*retry Apply query & run/, "a successfully executed but unsaved query must remain explicitly retryable");
assert.match(source, /function renderQueryResult\(card, widget\)[\s\S]*execution\.result\.columns[\s\S]*execution\.result\.rows/, "live aggregate results must render from server-returned columns and rows");
assert.match(source, /visibleColumns[\s\S]*item\.presentation\.hidden[\s\S]*pageCount[\s\S]*rows\.slice[\s\S]*aggregate-report-table[\s\S]*classList\.add\("pinned"\)/, "aggregate report rendering must honor visibility, bounded pagination, widths, and pinning");
assert.match(source, /widgetVisualizationDraft = reconcileVisualization\(widgetQueryDraft, widget\.configuration\?\.visualization\)[\s\S]*const visualizationDraft = reconcileVisualization\(draft, clone\(widgetVisualizationDraft\)\)[\s\S]*widget\.configuration = \{ source, query: draft, table: tableDraft, visualization: visualizationDraft, detail: detailDraft \}/, "visualization changes must remain draft state until the verified query is applied and saved");
assert.match(source, /renderKpiVisualization[\s\S]*renderBarVisualization[\s\S]*renderLineVisualization[\s\S]*renderDonutVisualization[\s\S]*visualization\.mode === "kpi"[\s\S]*visualization\.mode === "donut"/, "live server results must dispatch to KPI, grouped bar, line, donut, and table renderers");
assert.match(source, /KPI groups require an ungrouped result[\s\S]*Grouped bars require one grouping dimension[\s\S]*Lines require one ordered grouping dimension[\s\S]*Donut charts require exactly one non-negative numeric measure/, "incompatible visualizations must explain missing or invalid roles without deleting query fields");
assert.match(source, /const savedVisualization = sameSource \? widget\.configuration\?\.visualization : null[\s\S]*savedVisualization \? \{ visualization: savedVisualization \}/, "reassigning the unchanged source must retain visualization state");
assert.match(source, /numericValue === null \? "auto"[\s\S]*classList\.toggle\("no-value"[\s\S]*const appendSegment[\s\S]*numericValue === null[\s\S]*appendSegment\(\)/, "bar and line charts must preserve SQL NULL gaps instead of drawing invented zero or minimum values");
assert.match(source, /if \(item\.numberFormat\.style === "currency"\) measureControls\.push\(queryLabel\("Currency"[\s\S]*if \(\["decimal", "currency", "percent"\]\.includes\(item\.numberFormat\.style\)\) measureControls\.push\(queryLabel\("Decimal places"/, "currency and decimal controls must render only for number formats that use them");
assert.match(source, /function visualizationDataTable[\s\S]*View chart data[\s\S]*aria-label[\s\S]*chart data/, "every chart needs an accessible bounded data-table representation");
assert.match(source, /dataset\.drillLineage = JSON\.stringify\(visualizationLineage/g, "live visualization marks must retain drill-through lineage hooks");
assert.match(source, /row\.dataset\.drillLineage[\s\S]*cell\.dataset\.drillLineage[\s\S]*filterGroups/, "aggregate rows and metric cells must retain drill-through lineage hooks");
assert.match(source, /executedSqlByResult\.set\(`\$\{widget\.id\}:widget`, \{ sql: result\.sql, parameters: result\.parameters \}\)/, "View SQL must retain exact server-returned query provenance");
const verificationSource = source.slice(source.indexOf("async function verifyDashboardSources"), source.indexOf("async function loadRelations"));
assert.doesNotMatch(verificationSource, /executionToken|widgetQueryExecutionTokens\.set/, "source verification must not create an out-of-scope widget execution token");
const executionSource = source.slice(source.indexOf("async function executeWidgetQuery"), source.indexOf("async function executeDashboardQueries"));
assert.ok(executionSource.indexOf("const executionToken") < executionSource.indexOf("widgetQueryExecutionTokens.get"), "widget query execution must create its race token before checking it");
assert.match(executionSource, /const tokenKey = `\$\{widget\.id\}:\$\{publish \? "publish" : "draft"\}`/, "saved-query refreshes and unpublished drafts need independent race tokens");
assert.match(executionSource, /const currentWidget =[\s\S]*sourceCurrent[\s\S]*queryCurrent[\s\S]*Query execution was superseded/, "stale query responses must not publish after source or query changes");
assert.match(source, /function invalidateWidgetRuntime\(widgetId\)[\s\S]*:publish[\s\S]*:draft[\s\S]*sourceVerificationGeneration \+= 1[\s\S]*queryExecutionGeneration \+= 1/, "source changes must invalidate query and verification work");
assert.match(source, /elements\.widgetSourceProfile\.value !== profile\.id/, "late namespace responses must not replace the selected profile catalog");
assert.match(source, /const applySession = \{ dashboardId, widgetId, generation: widgetEditorGeneration \}[\s\S]*widgetEditorGeneration !== applySession\.generation/, "a stale apply must not overwrite a reopened widget editor");
assert.match(source, /event\.key !== "Escape"[\s\S]*!calendarClosed && focusedWidgetId/, "Escape must close calendars first and then the expanded widget workspace");
assert.match(source, /error\.code === "invalid_dashboard"[\s\S]*Invalid layout restored/, "invalid client layouts must restore the last persisted dashboard");
const persistSource = source.slice(source.indexOf("async function persistDashboard"), source.indexOf("async function flushPendingSave"));
assert.ok(persistSource.indexOf("const snapshot = clone(activeDashboard)") > persistSource.indexOf("saveQueue = saveQueue"), "queued saves must capture the revision only after prior saves finish");
assert.match(source, /saveTimerDashboardId = dashboardId[\s\S]*activeDashboard\?\.id === dashboardId[\s\S]*persistDashboard\(dashboardId\)/, "debounced saves must remain bound to the dashboard that scheduled them");
assert.match(persistSource, /setSaveStatus\("Save failed", "error"\)[\s\S]*throw error;/, "save failures must remain visible and reject navigation callers");
assert.match(source, /button\.addEventListener\("click", async \(\) => \{[\s\S]*await flushPendingSave\(\)[\s\S]*openDashboard\(record\.id\)[\s\S]*navigation was blocked/, "desktop dashboard navigation must stop when pending persistence fails");
assert.match(source, /mobileDashboardSelect\.addEventListener\("change"[\s\S]*await flushPendingSave\(\)[\s\S]*mobileDashboardSelect\.value = activeDashboard\?\.id/, "mobile dashboard navigation must restore its selection after a failed save");
assert.match(source, /const previousTitle = activeDashboard\?\.dashboard\.title[\s\S]*formAction === "rename"[\s\S]*activeDashboard\.dashboard\.title = previousTitle/, "failed dashboard renames must restore the local title");
assert.match(source, /async function archiveDashboard\(\)[\s\S]*await persistDashboard\(\)[\s\S]*activeDashboard\.dashboard\.archived = !archived/, "failed archive changes must remain on the current dashboard and restore local state");
assert.match(source, /formAction === "create"|action === "create"/, "create dashboard behavior is missing");
for (const operation of ["rename", "duplicate", "archive", "delete"]) assert.match(source, new RegExp(`#${operation}-dashboard`), `${operation} dashboard behavior is missing`);
assert.match(styles, /^@import url\("\/shared\/theme\.css"\);/, "Schemer must use the shared visual theme");
assert.match(source, /connections-button[\s\S]*icon: "database"[\s\S]*edit-mode-button[\s\S]*icon: "edit"[\s\S]*add-widget-button[\s\S]*icon: "add"[\s\S]*refresh-button[\s\S]*icon: "refresh"[\s\S]*decorateIconControl[\s\S]*icon: "more"/, "Schemer toolbar actions must use shared graphical controls with tooltips");
assert.match(styles, /\.dashboard-canvas \{ grid-template-columns: repeat\(auto-fit, minmax\(240px, 1fr\)\); grid-auto-rows: 260px;/, "dashboard cards must use a uniform responsive grid");
assert.match(styles, /\.widget\.swap-target \{[^}]*border-color: var\(--accent\)/, "the widget under the dragged center needs a visible swap affordance");
assert.match(styles, /\.widget-focus \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/, "metric inspection must split widget and population views evenly");
assert.match(styles, /\.widget-focus \{[^}]*position: fixed;[^}]*inset: 40px 0 0;/, "expanded widgets must cover the dashboard and sidebar below the app header");
assert.match(styles, /\.population-table \{[^}]*border-collapse: collapse/, "the inspector must render a structured population table");
assert.match(styles, /content: attr\(data-bar-value\)[\s\S]*content: attr\(data-bar-label\)/, "expanded KPI bars must display their values and date labels");
assert.match(styles, /\.population-filter-row \{[^}]*display: grid/, "applied filters must be shown as distinct field/value rows");
assert.match(styles, /\.executed-sql-dialog \{[^}]*width: min\(900px/, "executed SQL must open in a readable popup");
assert.match(styles, /\.relation-assignment \{[^}]*display: grid/, "relation details need a clear widget assignment control");
assert.match(styles, /\.column-suggestions \{[^}]*display: flex/, "advisory column roles need a distinct visual treatment");
assert.match(styles, /\.relation-preview-data \{[^}]*overflow: auto/, "bounded source rows need a contained preview surface");
assert.match(styles, /\.widget-editor-layout \{[^}]*grid-template: auto minmax\(0, 1fr\) \/ minmax\(0, 1fr\);[^}]*overflow: hidden;/, "widget configuration needs top tabs and one bounded content pane");
assert.match(styles, /\.widget-editor-nav \{[^}]*display: flex;/, "widget configuration tabs need a connected filing-cabinet strip");
assert.match(styles, /\.widget-editor-nav button\.active \{[^}]*margin-bottom: -1px;[^}]*border-color: #5b4921 #5b4921 #10151c;/, "the active filing tab must visually connect to its content");
assert.match(styles, /\.widget-editor-nav button:not\(\.active\):hover, \.widget-editor-nav button:not\(\.active\):focus-visible \{[^}]*color: #f0dfad;[^}]*border-color: #66552a;[^}]*background: #211b10;/, "inactive widget editor tabs need visible hover and keyboard-focus highlighting");
assert.match(styles, /\.widget-editor-nav \{[^}]*overflow-y: hidden;[^}]*scrollbar-width: none;[^}]*\}[\s\S]*\.widget-editor-nav::\-webkit-scrollbar \{[^}]*display: none;/, "the widget editor tab strip must scroll without exposing another scrollbar");
assert.match(styles, /\.widget-editor-dialog \{[^}]*overflow: hidden;/, "the editor dialog itself must not create a second scrollbar");
assert.match(styles, /\.widget-editor-name \{[^}]*height: 34px;[^}]*border: 1px solid #2b3440;[^}]*background: #151a22;[^}]*font-size: 17px;/, "the editable widget name must use the inspector control treatment");
assert.match(styles, /\.query-editor-row \{[^}]*minmax\(150px, 280px\)[^}]*justify-content: start;/, "query controls must stay compact rather than stretching across the view");
assert.match(styles, /\.query-editor-row \{[^}]*grid-template-columns:/, "structured query fields need responsive editor rows");
assert.match(styles, /\.sort-priority \{[^}]*grid-template-columns: 1fr 1fr/, "sort rows need visible ordering controls");
assert.match(styles, /\.query-result-scroll \{[^}]*overflow: auto/, "aggregate result tables need a bounded scrolling surface");
assert.match(styles, /\.grouping-picker > div \{[^}]*position: absolute/, "grouping choices need a contained dropdown surface");
assert.match(styles, /\.grouping-picker > summary \{[^}]*height: 34px;[^}]*padding: 0 9px;[^}]*border: 1px solid #2b3440;[^}]*border-radius: 5px;[^}]*background: #151a22;[^}]*font-size: 11px;/, "the grouping trigger must match Schemii inspector selects");
assert.match(styles, /\.grouping-picker > summary::after \{[^}]*width: 7px;[^}]*height: 7px;[^}]*border-right: 2px solid #aeb8c5;[^}]*border-bottom: 2px solid #aeb8c5;[^}]*content: "";[^}]*rotate\(45deg\)/, "the grouping trigger must use the native-select chevron shape rather than a text glyph");
assert.match(styles, /\.filter-condition-group \{[^}]*border:/, "AND conditions need a visible filter-group boundary");
assert.match(styles, /\.filter-between-values \{[^}]*grid-template-columns: 1fr 1fr/, "between bounds need a paired responsive layout");
assert.match(styles, /\.query-calendar-popup \{[^}]*background: #10151c;[^}]*box-shadow:/, "the custom calendar needs the Schemer popup theme");
assert.match(styles, /\.connection-layout input,[^}]*\.widget-editor-dialog select, \.grouping-picker > summary \{[^}]*height: 34px;[^}]*padding: 0 9px;[^}]*border: 1px solid #2b3440;[^}]*border-radius: 5px;[^}]*color: #d3dae3;[^}]*background: #151a22;[^}]*font-size: 11px;/, "widget and connection controls must share Schemii inspector styling");
assert.match(styles, /\.connection-layout input:focus,[^}]*\.widget-editor-dialog select:focus,[^}]*\.grouping-picker > summary:focus \{[^}]*border-color: #80682e;[^}]*box-shadow: 0 0 0 2px rgba\(244,185,66,\.08\);/, "widget control focus must match Schemii inspector controls");
assert.doesNotMatch(styles, /\.widget-editor-dialog select option(?::checked)?\s*\{/, "widget dropdown options must retain Schemii's native browser selection styling");
assert.match(styles, /Shared Schemii control geometry[\s\S]*\.query-remove, \.sort-order-button, \.query-calendar-toggle \{[^}]*height: 34px;[^}]*font-size: 10px;/, "query actions must share Schemii control geometry");
assert.match(styles, /\.aggregate-report-table \{[^}]*width: max-content !important;[^}]*table-layout: fixed;/, "aggregate reports need stable user-controlled column widths");
assert.match(styles, /\.aggregate-report-table \.pinned \{[^}]*position: sticky;/, "pinned aggregate report columns must remain visible while scrolling");
assert.match(styles, /\.query-result-pagination \{[^}]*display: flex;/, "aggregate reports need bounded pagination controls");
assert.match(styles, /\.widget-source-editor, \.widget-query-editor \{[^}]*scrollbar-width: none;[^}]*\}[\s\S]*\.widget-source-editor \.relation-list, \.widget-source-editor \.relation-detail \{[^}]*max-height: none;[^}]*overflow: visible;/, "the widget editor must use one hidden-scrollbar content flow instead of nested relation scroll panes");
assert.match(styles, /\.visualization-editor-row \{[^}]*grid-template-columns: minmax\(180px, 280px\) minmax\(0, 1fr\);[^}]*align-items: stretch;[\s\S]*\.visualization-editor-row \.visualization-sample \{[^}]*width: min\(420px, 100%\);[^}]*justify-self: center;/, "the appearance sample must center within the space between the view selector and container edge");
assert.match(styles, /\.visualization-sample \{[^}]*grid-template-columns: minmax\(170px, 250px\) minmax\(120px, 1fr\);[\s\S]*\.visualization-sample figcaption \{[^}]*align-content: center;[^}]*border-left:/, "visualization descriptions must sit beside the sample graphic in a separated column");
assert.match(styles, /\.visualization-sample figcaption > strong, \.visualization-sample figcaption > span, \.visualization-sample figcaption > small \{[^}]*height: auto;[^}]*border: 0;[^}]*background: none;/, "decorative chart mark styles must not leak into visualization descriptions");
assert.match(styles, /\.visualization-sample \{[^}]*grid-template-columns: minmax\(170px, 250px\) minmax\(120px, 1fr\);[\s\S]*\.visualization-sample-bar[\s\S]*\.visualization-sample-line[\s\S]*\.visualization-sample-donut/, "static table, KPI, bar, line, and donut samples need distinct visual treatments");
assert.match(styles, /\.query-editor-group\.visualization-role-linked \{[^}]*border-color:[^}]*box-shadow:[\s\S]*\.query-editor-group\.visualization-role-required \{[^}]*border-color:[^}]*box-shadow:/, "visualization-linked and required query roles need visible highlighting");
assert.match(styles, /\.live-kpi-group \{[^}]*grid-template-columns: repeat\(auto-fit/, "KPI mode must support multiple measures responsively");
assert.match(styles, /\.live-bar-chart \{[^}]*overflow: auto[\s\S]*\.live-line-chart \{[^}]*flex: 1[\s\S]*\.live-donut-layout \{[^}]*grid-template-columns:/, "bar, line, and donut results need bounded responsive layouts");
assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*transition-duration: \.01ms !important/, "Schemer must respect reduced-motion preferences");
assert.match(widgetEditor, /data-editor-section="detail">Detail Report</, "detail reports need a dedicated editor tab");
assert.match(html, /id="detail-drawer"[\s\S]*id="expand-detail-report"[\s\S]*id="view-detail-sql"/, "detail reports need a header-switchable pane with their own View SQL action");
assert.doesNotMatch(html, /detail-fullscreen|open-detail-fullscreen|close-detail-drawer|SQL provenance/, "the shared detail pane must not duplicate full-screen, close, or footer SQL actions");
assert.match(source, /function defaultDetailReport\(source\)[\s\S]*version: 1[\s\S]*slice\(0, 64\)[\s\S]*sourceColumn: column\.name[\s\S]*label: column\.name[\s\S]*width: 160[\s\S]*hidden: false[\s\S]*searchable:[\s\S]*numberFormat: \{ style: "auto" \}[\s\S]*defaultSort: null[\s\S]*rowIdentifier: null[\s\S]*pageSize: 25/, "detail drafts need deterministic bounded defaults");
assert.match(source, /function reconcileDetailReport\(source, detail = null\)[\s\S]*orderedNames[\s\S]*sourceColumn[\s\S]*defaultSort[\s\S]*rowIdentifier[\s\S]*pageSize/, "detail drafts must reconcile saved presentation against the exact current source columns");
const detailEditorSource = source.slice(source.indexOf("function editorDetailSection"), source.indexOf("function markVisualizationRole"));
for (const control of ["Display label", "Width (px)", "Show", "Searchable", "Number format", "Row identifier", "Default sort", "Rows per page"]) assert.match(detailEditorSource, new RegExp(control.replace(/[()]/g, "\\$&")), `the Detail Report tab must expose ${control}`);
assert.match(source, /const detailDraft = reconcileDetailReport\(source, clone\(widgetDetailDraft\)\)[\s\S]*await executeWidgetQuery[\s\S]*widget\.configuration = \{ source, query: draft, table: tableDraft, visualization: visualizationDraft, detail: detailDraft \}/, "detail configuration must persist only after successful query execution");
const detailRequestSource = source.slice(source.indexOf("async function requestDetailReport"), source.indexOf("function openDetailReport"));
assert.match(detailRequestSource, /detailColumns = context\.detail\.columns\.map[\s\S]*id: `detail_column_\$\{index \+ 1\}`[\s\S]*column: column\.sourceColumn[\s\S]*numberFormat: clone\(column\.numberFormat\)[\s\S]*requestSort[\s\S]*source: clone\(context\.source\), query: clone\(context\.query\), selection: clone\(context\.selection\), detail: requestDetail,[\s\S]*offset: context\.offset, limit: context\.limit, sort: requestSort, search: context\.search/, "detail POST bodies must transform presentation into the complete bounded server contract");
assert.match(detailRequestSource, /\/relation\/detail`[\s\S]*method: "POST"[\s\S]*detailRequestToken === token[\s\S]*activeDashboard\?\.id === context\.dashboardId[\s\S]*JSON\.stringify\(widget\.configuration\?\.source\)[\s\S]*queryForVisualization/, "detail requests must reject stale dashboard, source, query, and race contexts");
const openDetailSource = source.slice(source.indexOf("function openDetailReport"), source.indexOf("function closeDetailReport"));
assert.match(openDetailSource, /dimensions: \(lineage\.dimensions[\s\S]*targetId: dimension\.targetId, value:[\s\S]*measureId: lineage\.measure\.id[\s\S]*query: queryForVisualization/, "drill selection must project the saved visualization query and carry dimensions plus an optional measure");
assert.doesNotMatch(openDetailSource, /slicer|controls|config:/, "detail drill-through must not integrate dashboard slicers or add fields outside the selection contract");
assert.match(source, /elements\.canvas\.addEventListener\("click"[\s\S]*const drillTarget = event\.target\.closest\("\[data-drill-lineage\]"\)[\s\S]*openDetailReport\(drillTarget, widgetId\)[\s\S]*openWidgetFocus/, "dashboard drill lineage must run before widget-focus fallback");
assert.match(source, /elements\.widgetFocusContent\.addEventListener\("click"[\s\S]*data-drill-lineage[\s\S]*openDetailReport[\s\S]*data-inspect-metric[\s\S]*inspectMetric/, "live drill lineage must run before the static preview inspector fallback");
assert.match(source, /row\.dataset\.drillLineage[\s\S]*row\.tabIndex = 0[\s\S]*role", "button"[\s\S]*cell\.dataset\.drillLineage/, "aggregate rows and cells must be keyboard-accessible drill targets");
assert.match(source, /function closeDetailReport[\s\S]*detailRequestToken = null[\s\S]*detailReturnFocus\?\.isConnected[\s\S]*focused-widget-pane-heading/, "closing detail must invalidate work and restore focus to a surviving drill target or widget heading");
assert.match(source, /detailContext\.query\.filters\.forEach[\s\S]*condition\.operator[\s\S]*elements\.detailFilters\.append/, "detail filter chips must show the widget filters already applied by the server");
assert.match(source, /dashboardQueriedAt[\s\S]*Dashboard [\s\S]*Detail /, "detail reports must distinguish the dashboard result time from the live detail query time");
for (const field of ["matchingRowCount", "hasMore", "queriedAt", "queryDurationMs"]) assert.match(source, new RegExp(field), `detail results must consume server ${field}`);
assert.match(source, /function openDetailSql\(\)[\s\S]*result\.sql[\s\S]*result\.parameters/, "detail results must expose SQL provenance");
assert.match(styles, /\.widget-focus\.detail-open \{[^}]*bottom: 74px[\s\S]*\.widget-focus\.detail-open\.detail-active \{[^}]*bottom: calc\(100vh - 104px\)[\s\S]*\.detail-drawer\.open \{[^}]*top: 112px[\s\S]*\.detail-drawer\.open\.collapsed \{[^}]*top: calc\(100vh - 66px\)/, "widget and detail panes must share vertical space and animate between expanded headers");
assert.match(styles, /\.detail-drawer \{[^}]*right: 12px;[^}]*bottom: 8px;[^}]*left: 12px;[^}]*border: 1px solid[^}]*border-radius: 9px;[^}]*transform: translateY\(calc\(100% \+ 8px\)\)/, "the detail report needs the same inset bordered bubble treatment as the widget pane");
assert.match(sharedStyles, /\.shared-icon-button, \.icon-button \{[^}]*width: 27px;[^}]*height: 27px;[^}]*border-radius: 5px;/, "Schemii and Schemer icon buttons must share one visual definition");
assert.match(sharedUi, /const ICONS = Object\.freeze[\s\S]*close:[\s\S]*sql:[\s\S]*function createIconButton[\s\S]*function createTooltipController/, "shared UI must own common SVG icons, button construction, and tooltip behavior");
assert.match(source, /sharedIconButton\(\{ icon: "sql"[\s\S]*sharedIconButton\(\{ icon: "close"/, "widget SQL and Close actions must use the shared icon-button factory");
assert.match(styles, /\.detail-report-head \{[^}]*gap: 8px;[^}]*padding: 9px 12px;[\s\S]*\.detail-report-head strong \{[^}]*font-size: 9px;[\s\S]*\.detail-report-head small \{[^}]*font-size: 7px;[\s\S]*\.detail-close-spacer \{[^}]*visibility: hidden;/, "detail header text and action alignment must match the widget header while reserving its shared Close column");
assert.match(source, /function setDetailPane\(pane\)[\s\S]*detail-active[\s\S]*collapsed[\s\S]*aria-expanded[\s\S]*\.inert = detailActive/, "pane headers must switch expanded content and keyboard state");
assert.match(source, /function toggleDetailPane\(\)[\s\S]*detail-active[\s\S]*\? "widget" : "detail"[\s\S]*detail-report-head[\s\S]*toggleDetailPane\(\)[\s\S]*focused-widget-pane-head[\s\S]*toggleDetailPane\(\)/, "either pane header must swap the expanded and minimized panes in both directions");
assert.match(source, /if \(focusedWidgetId !== widget\.id\) openWidgetFocus\(widget\.id\)[\s\S]*setDetailPane\("detail"\)/, "chart and table drill targets must automatically open the expanded detail pane");
assert.match(styles, /@media \(prefers-reduced-motion: reduce\) \{[^}]*\.widget-focus[^}]*\.detail-drawer \{ transition: none;/, "detail pane motion must respect reduced-motion preferences");
assert.match(html, /role="tablist"[\s\S]*role="tab"[\s\S]*role="tabpanel"/, "widget editor sections must expose tab semantics");
assert.match(source, /aria-selected[\s\S]*button\.tabIndex = active \? 0 : -1[\s\S]*ArrowLeft[\s\S]*ArrowRight/, "widget editor tabs need selected state and keyboard navigation");
assert.match(source, /widgetInspector\.inert = true[\s\S]*aria-hidden[\s\S]*widgetInspector\.inert = false/, "dismissed inspector controls must leave the keyboard focus order");
assert.match(html, /class="mobile-dashboard-nav"[\s\S]*id="mobile-dashboard-select"[\s\S]*id="mobile-new-dashboard"/, "narrow layouts need dashboard switching and creation controls");
assert.match(source, /mobileDashboardSelect\.replaceChildren[\s\S]*mobileDashboardSelect\.addEventListener\("change"[\s\S]*flushPendingSave\(\)/, "mobile dashboard navigation must render saved dashboards and flush edits before switching");
assert.match(source, /elements\.canvas\.inert = true[\s\S]*\.topbar"\)\.inert = true[\s\S]*elements\.canvas\.inert = false[\s\S]*\.topbar"\)\.inert = false/, "expanded widgets must isolate focus from the covered dashboard");
assert.match(source, /relation-preview-data[\s\S]*Source row preview[\s\S]*query-result-scroll[\s\S]*query results[\s\S]*population-table-scroll[\s\S]*Selected population rows/, "scrolling data regions must be keyboard focusable and labelled");
assert.match(styles, /\.relation-change-notice \{[^}]*border: 1px solid #713a42/, "missing or changed source metadata needs a prominent editor warning");
assert.match(styles, /\.dashboard-canvas \.widget\.source-invalid \{[^}]*cursor: not-allowed/, "stale or unavailable sources need a visible blocked state");
assert.match(styles, /\.focused-widget-body \{[^}]*flex: 1;[^}]*justify-content: center;/, "expanded graphics must be centered in the available widget body");
assert.match(styles, /\.widget-inspector \{[^}]*padding: 18px;[^}]*background-image:/, "the inspector must use the same floating workspace treatment as the widget");
assert.match(styles, /\.widget-inspector-body \{[^}]*border-radius: 0 0 8px 8px;[^}]*linear-gradient/, "the inspector header and table must form one floating card");
assert.match(schemiiStyles, /^@import url\("\/shared\/theme\.css"\);/, "Schemii must use the same visual theme");
assert.match(client, /path\.startsWith\("\/api\/postgres\/"\)/, "the shared client must restrict PostgreSQL requests to the local API");
assert.match(sessionClient, /X-Schemii-Token/, "the shared session client must preserve the existing session contract");

console.log("Schemer shared connection and dashboard contracts passed");
