const assert = require("node:assert/strict");
const fs = require("node:fs");

const source = fs.readFileSync("src/schemii/schemer_web/app.js", "utf8");
const html = fs.readFileSync("src/schemii/schemer_web/index.html", "utf8");
const styles = fs.readFileSync("src/schemii/schemer_web/styles.css", "utf8");
const schemiiStyles = fs.readFileSync("src/schemii/web/styles.css", "utf8");
const client = fs.readFileSync("src/schemii/shared_web/postgres-client.js", "utf8");
const connectionDialog = html.slice(html.indexOf('id="connections-dialog"'), html.indexOf('id="dashboard-form-dialog"'));
const widgetEditor = html.slice(html.indexOf('id="widget-editor-dialog"'), html.indexOf('id="executed-sql-dialog"'));

assert.match(html, /<title>Schemer<\/title>/, "Schemer needs its own browser identity");
assert.match(html, /\/shared\/postgres-client\.js/, "Schemer must load the shared PostgreSQL browser client");
assert.match(source, /SchemiiShared\.createPostgresClient/, "Schemer must instantiate the shared PostgreSQL client");
assert.match(source, /path\.startsWith\("\/api\/dashboards"\)/, "dashboard requests must stay on the local Schemer API");
assert.match(source, /postgres\.request\("\/api\/postgres\/profiles"\)/, "PostgreSQL requests must use the shared browser client");
assert.match(source, /postgres\.request\(`\/api\/postgres\/profiles\/\$\{encodeURIComponent\(profile\.id\)\}\/relations\?database=\$\{encodeURIComponent\(profile\.dbname\)\}&namespace=\$\{encodeURIComponent\(namespace\)\}`\)/, "relation browsing must use the shared exact-database catalog route");
assert.match(source, /postgres\.request\(`\/api\/postgres\/profiles\/\$\{encodeURIComponent\(catalog\.profileId\)\}\/relation\?database=[\s\S]*&relation=\$\{encodeURIComponent\(relation\.name\)\}`\)/, "relation selection must inspect one exact catalog identity");
assert.match(source, /selectedRelationIdentity = \{[\s\S]*profileId: descriptor\.profileId,[\s\S]*database: descriptor\.database,[\s\S]*namespace: descriptor\.namespace,[\s\S]*relation: descriptor\.relation,[\s\S]*kind: descriptor\.kind,[\s\S]*fingerprint: descriptor\.fingerprint/, "inspected relation identity must retain its stable catalog fingerprint");
assert.doesNotMatch(connectionDialog, /relation-browser/, "global Data sources must remain connection management only");
assert.match(widgetEditor, /relation-browser[\s\S]*Tables, views, and materialized views/, "each widget editor needs its own supported relation browser");
assert.match(widgetEditor, />Groupings[\s\S]*>Filters/, "the widget editor must remain the home for grouping and filter configuration");
assert.match(source, /for \(const label of \["#", "Column", "PostgreSQL type", "Nullability", "Suggested roles"\]\)/, "relation inspection must display ordered PostgreSQL column metadata and advisory roles");
assert.match(source, /for \(const suggestion of column\.suggestions\)[\s\S]*badge\.textContent = suggestion/, "column role suggestions must render as advisory labels");
assert.doesNotMatch(source, /widget\.configuration\.(?:dimension|measure|date|identifier)|widget\.configuration\[["'](?:dimension|measure|date|identifier)/, "role suggestions must not silently change widget configuration");
assert.match(source, /\/relation\/preview`[\s\S]*method: "POST"[\s\S]*source: exactSourceIdentity\(descriptor\), offset: 0, limit: 20/, "source preview must send one verified identity with an explicit bound");
assert.match(source, /function renderRelationPreview\(result, container\)[\s\S]*for \(const column of result\.columns\)[\s\S]*result\.rows/, "source preview must render bounded rows through DOM APIs");
assert.match(html, /class="relation-detail" id="relation-detail"/, "the relation browser needs a catalog detail pane");
assert.match(source, /function exactSourceIdentity\(descriptor\)[\s\S]*profileId: descriptor\.profileId[\s\S]*fingerprint: descriptor\.fingerprint[\s\S]*widget\.configuration = \{ source: exactSourceIdentity\(descriptor\) \}[\s\S]*markDashboardChanged\(true\)/, "Edit mode must assign exactly one verified source identity to a widget");
assert.match(source, /function openWidgetEditor\(widgetId\)[\s\S]*edit\.dataset\.action = "edit-widget"/, "every Edit-mode tile must open its own widget editor");
assert.match(source, /const widget = activeDashboard\?\.dashboard\.widgets\.find\(item => item\.id === editedWidgetId\)[\s\S]*widget\.configuration = \{ source: exactSourceIdentity\(descriptor\) \}/, "source assignment must target only the widget being edited");
assert.doesNotMatch(source, /widgetSelect|Widget receiving this source/, "the widget editor must not assign one widget's source through a global widget picker");
assert.match(source, /function openWidgetEditor\(widgetId\)[\s\S]*relationDetail\.replaceChildren\(\)[\s\S]*relationDetail\.hidden = true[\s\S]*currentSource[\s\S]*inspectSelectedRelation\(catalog, relation\)/, "widget editor reopen must clear stale controls and restore only that widget's saved source");
assert.match(source, /assign\.disabled = !editMode[\s\S]*widget\.configuration = \{\}/, "View mode must not assign sources and Edit mode must support clearing one");
assert.match(source, /sourceLabel\.textContent = `\$\{source\.database\}\.\$\{source\.namespace\}\.\$\{source\.relation\}\$\{suffix\}`/, "sourced widgets must display their exact relation identity and verification state");
assert.match(source, /function sourceVerificationPath\(source\)[\s\S]*expectedKind=\$\{encodeURIComponent\(source\.kind\)\}[\s\S]*expectedFingerprint=\$\{encodeURIComponent\(source\.fingerprint\)\}/, "live source checks must require the saved relation kind and fingerprint");
assert.match(source, /async function verifyDashboardSources\(\)[\s\S]*state: "checking"[\s\S]*code: error\.code[\s\S]*renderDashboard\(\)/, "dashboard loading must visibly verify every persisted source");
assert.match(source, /widget\.configuration\?\.source && verification\?\.state !== "verified"[\s\S]*return;/, "unverified or stale widget sources must not open results");
assert.match(source, /if \(profilesLoading\) return profilesLoading[\s\S]*generation !== relationCatalogGeneration/, "concurrent profile and relation loads must not clear newer catalog inspection state");
assert.match(source, /connections-button[\s\S]*if \(!profiles\.length\) await loadProfiles\(\)/, "opening an already loaded source browser must not clear its inspected relation");
assert.match(source, /replaceChildren/, "connection metadata must render through DOM APIs");
assert.doesNotMatch(source, /innerHTML|insertAdjacentHTML|eval\(/, "connection metadata must not be interpreted as code or HTML");
assert.match(source, /dashboard_conflict/, "stale dashboard writes must stop autosave");
assert.match(source, /dashboard\.viewport\[mode\]/, "desktop and mobile viewport state must be stored independently");
assert.match(source, /classList\.toggle\("button-ghost", !editMode\)/, "Finish editing must not retain the conflicting ghost-button style");
assert.doesNotMatch(source, /pointerdown|pointermove|pointerup|widget-resize-handle|reorderDesktopWidget|packDesktopLayout/, "dashboard cards must not support freeform positioning or resizing");
assert.match(source, /card\.draggable = editMode[\s\S]*addEventListener\("dragstart"[\s\S]*addEventListener\("drop"/, "Edit mode must support drag-and-drop tile ordering");
assert.match(source, /function swapWidgets\(widgetId, targetId\)[\s\S]*\[widgets\[sourceIndex\], widgets\[targetIndex\]\]/, "center overlap must swap the dragged and target widgets in the dashboard model");
assert.match(source, /dragCenterOffset[\s\S]*center\.x >= rect\.left[\s\S]*center\.y <= rect\.bottom/, "swap detection must use the dragged widget center crossing a target widget");
assert.match(source, /function animateWidgetSwap\(previousRects\)[\s\S]*card\.animate\(\[\{ transform:[\s\S]*duration: 260/, "widget swaps must animate from their previous grid positions");
assert.match(source, /function finishWidgetDrag\(\)[\s\S]*persistWidgetOrder\(activeDashboard\.dashboard\.widgets, false\)/, "animated swaps must persist when dragging finishes without interrupting the animation");
assert.match(source, /move-widget-earlier[\s\S]*move-widget-later/, "tile ordering must also provide keyboard-accessible controls");
assert.match(source, /widget\.layout\.mobile\.order = index/, "reordering must keep mobile ordering aligned with the widget sequence");
assert.match(html, /id="widget-focus"[\s\S]*id="widget-inspector"/, "expanded widgets need a workspace view and inspector drawer");
assert.doesNotMatch(html, /widget-focus-head|close-widget-focus/, "expanded widgets must use their own header rather than a redundant outer header");
assert.match(source, /function openWidgetFocus\(widgetId\)/, "dashboard cards must open the expanded widget workspace");
assert.match(source, /openWidgetFocus\(card\.dataset\.widgetId\)/, "keyboard activation must open the expanded widget workspace");
assert.match(source, /focusedSourceRect = sourceCard\?\.getBoundingClientRect\(\)/, "expanded widgets must animate from the selected tile geometry");
assert.match(source, /focusedSourceRect\.width \/ target\.width[\s\S]*scale\(1\)/, "expanded widgets must scale from the tile instead of sliding in");
assert.match(source, /widgetInspector\.classList\.add\("dismissed"\)[\s\S]*widgetFocus\.classList\.add\("inspector-dismissed"\)/, "tile expansion must start without the inspector drawer");
assert.match(source, /\[data-inspect-metric\]/, "only metric-level targets may open the widget inspector");
assert.match(source, /\.metric-sparkline i[\s\S]*\.status-legend > span[\s\S]*querySelectorAll\("tbody tr"\)/, "bars, status values, and table rows must be individually inspectable");
assert.match(source, /function populationTable\(filters\)/, "metric inspection must render the selected population as a table");
assert.match(source, /const DATE_BUCKETS = \["Jun 1–4"[\s\S]*"Jun 28–30"\]/, "KPI bars must represent explicit order-date buckets");
assert.match(source, /bar\.dataset\.barLabel = date[\s\S]*bar\.dataset\.barValue = amount/, "expanded KPI bars must expose their date and value labels");
assert.match(source, /field: "Order date"[\s\S]*field: "Bucket value"/, "KPI bar selections must expose structured filters");
assert.match(source, /function populationRows\(filters\)[\s\S]*row\[6\] >= Number\(dates\[1\]\)/, "preview populations must filter by the selected date bucket");
assert.match(html, /id="view-inspector-sql"[\s\S]*id="executed-sql-dialog"/, "population results need an executed-SQL popup");
assert.match(source, /viewSql\.dataset\.action = "view-widget-sql"/, "every widget tile needs a View SQL button");
assert.match(source, /executedSqlByResult\.get\(`\$\{widget\.id\}:\$\{population \? "population" : "widget"\}`\)/, "widget and population results must use separate SQL provenance");
assert.match(source, /No SQL was executed for this static preview result/, "preview widgets must not claim that invented SQL was executed");
assert.match(source, /execution\?\.sql[\s\S]*execution\?\.parameters/, "the popup must show the executed parameterized statement and its bound values");
assert.match(source, /event\.key === "Escape" && focusedWidgetId/, "Escape must close the expanded widget workspace");
assert.match(source, /error\.code === "invalid_dashboard"[\s\S]*Invalid layout restored/, "invalid client layouts must restore the last persisted dashboard");
const persistSource = source.slice(source.indexOf("async function persistDashboard"), source.indexOf("async function flushPendingSave"));
assert.ok(persistSource.indexOf("const snapshot = clone(activeDashboard)") > persistSource.indexOf("saveQueue = saveQueue"), "queued saves must capture the revision only after prior saves finish");
assert.match(source, /formAction === "create"|action === "create"/, "create dashboard behavior is missing");
for (const operation of ["rename", "duplicate", "archive", "delete"]) assert.match(source, new RegExp(`#${operation}-dashboard`), `${operation} dashboard behavior is missing`);
assert.match(styles, /^@import url\("\/shared\/theme\.css"\);/, "Schemer must use the shared visual theme");
assert.match(styles, /#edit-mode-button\.button-primary \{[^}]*color: #fff4d6;[^}]*background: #76540e;/, "Finish editing needs an explicit high-contrast treatment");
assert.match(styles, /\.dashboard-canvas \{ grid-template-columns: repeat\(auto-fit, minmax\(240px, 1fr\)\); grid-auto-rows: 260px;/, "dashboard cards must use a uniform responsive grid");
assert.match(styles, /\.widget\.swap-target \{[^}]*border-color: var\(--accent\)/, "the widget under the dragged center needs a visible swap affordance");
assert.match(styles, /\.widget-focus \{[^}]*grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/, "metric inspection must split widget and population views evenly");
assert.match(styles, /\.widget-focus \{[^}]*position: fixed;[^}]*inset: 40px 0 0;/, "expanded widgets must cover the dashboard and sidebar below the app header");
assert.match(styles, /\.population-table \{[^}]*border-collapse: collapse/, "the inspector must render a structured population table");
assert.match(styles, /content: attr\(data-bar-value\)[\s\S]*content: attr\(data-bar-label\)/, "expanded KPI bars must display their values and date labels");
assert.match(styles, /\.population-filter-row \{[^}]*display: grid/, "applied filters must be shown as distinct field/value rows");
assert.match(styles, /\.executed-sql-dialog \{[^}]*width: min\(900px/, "executed SQL must open in a readable popup");
assert.match(styles, /\.relation-assignment \{[^}]*display: grid/, "relation details need a clear widget assignment control");
assert.match(styles, /\.column-suggestions \{[^}]*display: flex/, "advisory column roles need a distinct visual treatment");
assert.match(styles, /\.relation-preview-data \{[^}]*overflow: auto/, "bounded source rows need a contained preview surface");
assert.match(styles, /\.widget-editor-layout \{[^}]*grid-template-columns: 175px minmax\(0, 1fr\)/, "widget configuration needs a dedicated editor layout");
assert.match(styles, /\.dashboard-canvas \.widget\.source-invalid \{[^}]*cursor: not-allowed/, "stale or unavailable sources need a visible blocked state");
assert.match(styles, /\.focused-widget-body \{[^}]*flex: 1;[^}]*justify-content: center;/, "expanded graphics must be centered in the available widget body");
assert.match(styles, /\.widget-inspector \{[^}]*padding: 18px;[^}]*background-image:/, "the inspector must use the same floating workspace treatment as the widget");
assert.match(styles, /\.widget-inspector-body \{[^}]*border-radius: 0 0 8px 8px;[^}]*linear-gradient/, "the inspector header and table must form one floating card");
assert.match(schemiiStyles, /^@import url\("\/shared\/theme\.css"\);/, "Schemii must use the same visual theme");
assert.match(client, /path\.startsWith\("\/api\/postgres\/"\)/, "the shared client must restrict PostgreSQL requests to the local API");
assert.match(client, /X-Schemii-Token/, "the shared client must preserve the existing session contract");

console.log("Schemer shared connection and dashboard contracts passed");
