const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("src/schemii/schemer_web/index.html", "utf8");
const source = fs.readFileSync("src/schemii/schemer_web/app.js", "utf8");
const shared = fs.readFileSync("src/schemii/shared_web/ai-assistant.js", "utf8");
const styles = fs.readFileSync("src/schemii/shared_web/ai-assistant.css", "utf8");

assert.match(html, /id="ai-button"[\s\S]*class="ai-panel"[\s\S]*data-ai="model"[\s\S]*data-ai="access"[\s\S]*data-ai="messages"[\s\S]*data-ai="prompt"/, "Schemer needs the canonical shared model, disclosure, chat, and composer UI");
assert.match(html, /id="ai-settings-dialog"[\s\S]*Connections apply to Schemii and Schemer[\s\S]*id="ai-history-dialog"[\s\S]*Schemii conversations remain separate/, "Schemer must explain shared provider credentials and separate chat history");
assert.match(html, /\/shared\/ai-assistant\.css[\s\S]*\/shared\/ai-assistant\.js/, "Schemer must load the shared AI client and visual shell");
assert.match(shared, /path\.startsWith\("\/api\/ai\/"\)/, "AI traffic must stay on Schemer's same-origin API");
assert.doesNotMatch(shared, /fetch\([^)]*(?:opencode|8080|provider\.)/i, "the browser must not call Schemii, OpenCode, or providers directly");
assert.match(shared, /localStorage\.setItem\(storageKey, normalized\)/, "browser storage may remember only a validated provider/model preference");
assert.equal((shared.match(/localStorage\.setItem\(/g) || []).length, 1, "provider credentials must never enter browser storage");
for (const safeAssignment of [/body\.textContent = String\(text/, /body\.textContent = part\.text/, /summary\.textContent = normalized\.summary/]) assert.match(shared, safeAssignment, "untrusted model content and proposals must render through textContent");
assert.doesNotMatch(shared, /innerHTML|eval\(|new Function/, "the AI renderer must not interpret model output as code or HTML");
assert.match(shared, /\/activity`[\s\S]*getReader\(\)/, "Schemer AI needs bounded same-origin live activity");
assert.match(shared, /event\.type === "part"/, "Schemer AI must render bounded activity parts");
for (const route of ["/api/ai/auth/api", "/api/ai/auth/oauth/authorize", "/api/ai/auth/oauth/callback"]) assert.ok(shared.includes(route), `${route} must be handled by the shared provider UI`);
assert.match(shared, /Disconnect .*This affects both Schemii and Schemer/, "shared provider disconnect must explain its cross-app effect");
assert.match(shared, /\/api\/ai\/sessions[\s\S]*renderHistory[\s\S]*session\.id[\s\S]*method: "DELETE"/, "Schemer needs persistent app-isolated chat history");
assert.match(source, /function schemerAiContextKey[\s\S]*context\.dashboardId[\s\S]*aiContextFingerprint/, "Schemer must bind data chats to dashboard, disclosure, and PostgreSQL target");
assert.match(source, /SCHEMER_CONTEXT:\$\{schemerAiContextKey\(context, accessLevel\)\}/, "Schemer must persist the context binding in session titles");
assert.match(shared, /binding\.key === currentKey[\s\S]*state\.sessionId = resumable \? session\.id : null/, "history may continue only in its original dashboard and disclosure context");
assert.match(source, /function validateSchemerAiAction[\s\S]*exactFields[\s\S]*expectedRevision[\s\S]*currentTitle/, "Schemer actions must use strict fields, revisions, and exact widget identity");
assert.match(source, /JSON\.stringify\(activeDashboard\) !== capture\.snapshot[\s\S]*Dashboard changed; request a fresh proposal/, "dashboard changes must invalidate captured proposals");
assert.match(source, /if \(!confirm\([\s\S]*await persistDashboard\(\)[\s\S]*activeDashboard = before/, "AI mutations require confirmation, successful persistence, and local rollback on failure");
assert.match(source, /widget_create[\s\S]*kind: "placeholder"[\s\S]*widget_duplicate[\s\S]*nextWidgetId\(\)[\s\S]*widget_delete/, "Schemer must generate widget IDs and placement rather than trusting model layout");
assert.match(source, /completeFields[\s\S]*sourceFields[\s\S]*visualizationMode[\s\S]*configured: true/, "complete widget proposals must use strict source, query, and visualization fields");
assert.match(source, /\["bar", "line", "donut"\][\s\S]*action\.query\.dimensions/, "chart proposals must include a grouping dimension");
assert.match(source, /async function createConfiguredSchemerAiWidget[\s\S]*expectedKind[\s\S]*expectedFingerprint[\s\S]*relation\/query[\s\S]*await persistDashboard\(\)[\s\S]*widgetQueryResults\.set/, "complete widgets must re-inspect and execute before one persisted creation, then publish their result");
assert.match(source, /relation\/query[\s\S]*dashboardId: capture\.dashboardId, expectedRevision: capture\.revision/, "complete widget query execution must remain revision-guarded");
assert.match(source, /measureIndexes[\s\S]*numericResultValue[\s\S]*cannot render as a \$\{visualization\.mode\} chart/, "complete chart widgets must validate their live result before persistence");
assert.match(source, /const widgetId = nextWidgetId\(\)[\s\S]*schemerAiPlacement[\s\S]*id: widgetId, kind: "aggregate_report"/, "Schemer must own configured widget IDs, kind, and placement");
assert.match(source, /saveStarted[\s\S]*Save outcome unknown: reload required[\s\S]*const persistedWidget = persisted\.dashboard\.widgets\.find/, "complete widget creation must reconcile ambiguous saves or require reload");
assert.match(source, /function schemerAiPlacement[\s\S]*y <= 999[\s\S]*widgets\.every[\s\S]*Object\.assign\(duplicate\.layout\.desktop, schemerAiPlacement/, "AI-created and duplicated widgets need bounded non-overlapping placement");
const messageAdapter = source.slice(source.indexOf("buildMessagePayload:"), source.indexOf("validateAction:"));
assert.doesNotMatch(messageAdapter, /password|connectionString|host|\buser\b|profileFingerprint/i, "Schemer AI messages must not expose connection credentials or local identity fingerprints");
assert.match(html, /value="data"[\s\S]*data-ai-query-warning/, "Schemer must expose an explicit data tier with a query safety warning");
assert.doesNotMatch(html, /allow-session/, "Schemer must require confirmation for every analytic query");
assert.match(source, /action\.type === "read_query"[\s\S]*action\.readOnly !== true[\s\S]*expectedRevision[\s\S]*buttonLabel: "Review & run query"/, "query proposals must be strict, read-only, revision-bound, and inert");
assert.match(source, /async function executeSchemerAiReadQuery[\s\S]*profileRepository\.list\(\)[\s\S]*if \(!confirm\([\s\S]*database: capture\.database, namespace: capture\.namespace, sql: action\.sql/, "every query must revalidate its target and require confirmation before execution");
assert.match(source, /persistedBefore[\s\S]*postgres\.request[\s\S]*currentAccess === "data"[\s\S]*persistedAfter[\s\S]*aiAssistant\.appendQueryResult\(result\)[\s\S]*aiAssistant\.sendMessage[\s\S]*queryResult: boundedSchemerAiQueryResult\(result\)/, "approved bounded results must stay pinned to their persisted dashboard, disclosure, and PostgreSQL target");
assert.match(source, /canViewSession: \(binding, currentKey\) => binding\.accessLevel !== "data" \|\| binding\.key === currentKey/, "data history must remain hidden outside its exact target context");
const boundStart = shared.indexOf("function boundedAiQueryResult");
const boundEnd = shared.indexOf("function createAiAssistant", boundStart);
const boundContext = require("node:vm").createContext({ TextEncoder });
require("node:vm").runInContext(`${shared.slice(boundStart, boundEnd)}\nthis.boundResult = boundedAiQueryResult;`, boundContext);
const oversizedRows = Array.from({ length: 100 }, () => ["x".repeat(2000)]);
const bounded = boundContext.boundResult({ columns: [{ name: "value" }], rows: oversizedRows, truncated: false }, { maxRows: 100, maxColumns: 50, maxBytes: 48 * 1024, envelope: { profileId: "shared", database: "demo", namespace: "public", maxRows: 100, maxColumns: 50, maxResultBytes: 256 * 1024 } });
assert.ok(new TextEncoder().encode(JSON.stringify(bounded)).length <= 48 * 1024, "model query results must obey the UTF-8 byte limit");
assert.equal(bounded.rowCount, bounded.rows.length, "bounded results must contain only whole rows");
assert.equal(bounded.truncated, true, "bounded results must disclose truncation");
assert.match(styles, /\.ai-panel \{[^}]*position: fixed;[^}]*left: 0;[^}]*translate3d\(-100%[\s\S]*\.ai-panel\.open[\s\S]*@media \(prefers-reduced-motion: reduce\)/, "the shared AI panel needs canonical left-drawer motion with a reduced-motion fallback");
for (const stateContract of [/root\.inert = !open/, /aria-hidden/, /aria-expanded/]) assert.match(shared, stateContract, "the shared drawer must synchronize inert and ARIA state");

console.log("Schemer AI isolation and action contracts passed");
